
<div class="contenedor">
    <div class="candidatas">
        <div class="row">
            <?php
            $c = new My\Entity\Candidata();
            foreach ($this->candidatas as $c):
                ?>
                <div class="col-md-2">
                    <figure class="candidata">
                        <?php
                        if ($c->getImagenes()[0] != null) {
                            ?>

                            <img src="<?php echo $this->baseUrl() . '/img/candidatas/' . $c->getImagenes()[0]->getUrl(); ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                            <?php
                        } else {
                            ?>
                            <img src="<?php echo $this->baseUrl() . '/img/candidatas/default.jpg'; ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                            <?php
                        }
                        ?>
                        
                        <figcaption>
                            <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3><?php echo $c->getNombre(); ?></h3></a>
                        </figcaption>
                    </figure>
                </div>
                <?php
            endforeach;
            ?>
            


        </div>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                    </div>
                    <div class="modal-body">
                        <center>
                            <img src="<?php echo $this->baseUrl() . '/img/candidatas/reina-perfil.jpg' ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                        </center>
                        <div class="descripcion_candidadta">
                            <h3>El Chilcal</h3>
                            <p><span>Nombre: </span>Camila Sol Morales</p>
                            <p><span>Edad: </span>21</p>
                            <p><span>Ojos: </span>Marrones</p>
                            <p><span>Cabello: </span>Castaño claro</p>
                            <p><span>Estudios: </span>Es estilista y cursará la carrera de periodismo</p>
                            <p><span>Hobby: </span>Pasar tiempo con amigos y ver obras de teatro</p>

                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
