
<div class="contenedor">
    <div class="candidatas">
        <div class="row">
            <?php
            $c = new My\Entity\Candidata();
            foreach ($this->candidatas as $c):
                ?>
                <div class="col-md-2">
                    <figure class="candidata">
                        <?php
                        if ($c->getImagenes()[0] != null) {
                            ?>

                            <img src="<?php echo $this->baseUrl() . '/img/candidatas/' . $c->getImagenes()[0]->getUrl(); ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                            <?php
                        } else {
                            ?>
                            <img src="<?php echo $this->baseUrl() . '/img/candidatas/default.jpg'; ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                            <?php
                        }
                        ?>
                        
                        <figcaption>
                            <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal<?php echo $c->getId_candidata(); ?>"><h3><?php echo $c->getNombre(); ?></h3></a>
                        </figcaption>
                    </figure>
                </div>
                <?php
            endforeach;
            ?>
            


        </div>
    </div>
</div>

<!-- Modal -->
<?php 

    foreach ($this->candidatas as $c):
        ?>
            <div class="modal fade" id="myModal<?php echo $c->getId_candidata();?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel"><?php echo $c->getDistrito(); ?></h4>
                        </div>
                        <div class="modal-body">
                            <center>
                                <img src="<?php echo $this->baseUrl() . '/img/candidatas/'.$c->getImagenes()[1]->getUrl(); ?>" alt="..." class="img-responsive img-thumbnail">
                            </center>
                            <div class="descripcion_candidadta" style="margin: 20px 50px;">
                                <p><strong>Nombre: </strong><?php echo $c->getNombre();?></p>
                                <p><strong>Edad: </strong><?php echo $c->getEdad();?></p>
                                <p><strong>Ojos: </strong><?php echo $c->getOjos();?></p>
                                <p><strong>Cabello: </strong><?php echo $c->getCabello();?></p>
                                <p><strong>Estudios: </strong><?php echo $c->getEstudios();?></p>
                                <p><strong>Hobby: </strong><?php echo $c->getHobby();?></p>

                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-info" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>

        <?php
    endforeach;

?>
