
<div class="contenedor">
    <div class="candidatas">
        <div class="row">

            <div class="col-md-2">
                <figure class="candidata">
                    <img src="<?php echo $this->baseUrl() . '/img/candidatas/reina-perfil-1 (1).jpg' ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Camila Sol Morales</h3></a>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-2">
                <figure class="candidata">
                    <img src="<?php echo $this->baseUrl() . '/img/candidatas/reina-perfil-1 (2).jpg' ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Camila Sol Morales</h3></a>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-2">
                <figure class="candidata">
                    <img src="<?php echo $this->baseUrl() . '/img/candidatas/reina-perfil-1 (3).jpg' ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Camila Sol Morales</h3></a>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-2">
                <figure class="candidata">
                    <img src="<?php echo $this->baseUrl() . '/img/candidatas/reina-perfil-1 (4).jpg' ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Camila Sol Morales</h3></a>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-2">
                <figure class="candidata">
                    <img src="<?php echo $this->baseUrl() . '/img/candidatas/reina-perfil-1 (5).jpg' ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Camila Sol Morales</h3></a>
                    </figcaption>
                </figure>
            </div>


            <!--        </div>
                    <div class="row candidatas">-->

            <div class="col-md-2">
                <figure class="candidata">
                    <img src="<?php echo $this->baseUrl() . '/img/candidatas/reina-perfil-1 (6).jpg' ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Camila Sol Morales</h3></a>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-2">
                <figure class="candidata">
                    <img src="<?php echo $this->baseUrl() . '/img/candidatas/reina-perfil-1 (7).jpg' ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Camila Sol Morales</h3></a>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-2">
                <figure class="candidata">
                    <img src="<?php echo $this->baseUrl() . '/img/candidatas/reina-perfil.jpg' ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Camila Sol Morales</h3></a>
                </figure>
            </div>
            <div class="col-md-2">
                <figure class="candidata">
                    <img src="<?php echo $this->baseUrl() . '/img/candidatas/reina-perfil.jpg' ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Camila Sol Morales</h3></a>
                    </figcaption>
                </figure>
            </div>
            <div class="col-md-2">
                <figure class="candidata">
                    <img src="<?php echo $this->baseUrl() . '/img/candidatas/reina-perfil.jpg' ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Camila Sol Morales</h3></a>
                    </figcaption>
                </figure>
            </div>


        </div>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                    </div>
                    <div class="modal-body">
                        <center>
                            <img src="<?php echo $this->baseUrl() . '/img/candidatas/reina-perfil.jpg' ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                        </center>
                        <div class="descripcion_candidadta">
                            <h3>El Chilcal</h3>
                            <p><span>Nombre: </span>Camila Sol Morales</p>
                            <p><span>Edad: </span>21</p>
                            <p><span>Ojos: </span>Marrones</p>
                            <p><span>Cabello: </span>Castaño claro</p>
                            <p><span>Estudios: </span>Es estilista y cursará la carrera de periodismo</p>
                            <p><span>Hobby: </span>Pasar tiempo con amigos y ver obras de teatro</p>

                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
