<div class="contenedor reina">
    <div class="row">
        <div class="col-sm-6 col-md-3">
            <div id="carousel-reina" class="carousel slide" data-ride="carousel">
                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="<?php echo $this->baseUrl() . '/img/reina/img1.jpg'; ?>"  class="thumbnail img_reina">
                    </div>
                    <div class="item">
                        <img src="<?php echo $this->baseUrl() . '/img/reina/img2.jpg'; ?>"  class="thumbnail img_reina">
                    </div>
                </div>

            </div>
        </div>
        <div class="col-md-8 presentacion-reina">
            <h1>Rocío Fuster, Reina departamental de la vendimia 2016</h1>
            <h4>Edad:</h4> <p>19 Años de Edad</p>
            <h4>Profeción:</h4> <p>Auxiliar de acompañante terapéutico. Segundo año de profesorado de educación primaria.</p>
            <h4>Ojos:</h4><p> Ojos marrones</p>
            <h4>Hobby:</h4> <p>Bailar Folklore</p>
        </div>
    </div>
    <!-- NUEVAS CANDIDATAS -->
    
    <div class="row">
        <div class="seccion-nuevas-reinas">
            <a href="<?php echo $this->url(array('controller' => 'vendimia', 'action' => 'candidatas')); ?>" class="btn btn-lg btn-info">Nuevas candidatas 2016</a>
        </div>
    </div>
    
    <!-- GALERIA -->
    <div class="row seccion-galeria">

        <div class="col-md-12">

            <center>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central1.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central1.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central2.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central2.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central3.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central3.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central1.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central1.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central2.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central2.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central3.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central3.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central1.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central1.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central2.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central2.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central3.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central3.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central1.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central1.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central2.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central2.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central3.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central3.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central1.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central1.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central2.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central2.jpg">
                </a>
                <a class="img-thumbnail" href="<?php echo $this->baseUrl(); ?>/img/galeria/fiesta-central3.jpg" title="Todas las candidatas" data-gallery>
                    <img src="<?php echo $this->baseUrl(); ?>/img/galeria/thumbnails/fiesta-central3.jpg">
                </a>
            </center>
            <!-- The Gallery as lightbox dialog, should be a child element of the document body -->
            <div id="blueimp-gallery" class="blueimp-gallery">
                <!-- The container for the modal slides -->
                <div class="slides"></div>
                <!-- Controls for the borderless lightbox -->
                <h3 class="title"></h3>
                <a class="prev">‹</a>
                <a class="next">›</a>
                <a class="close">×</a>
                <a class="play-pause"></a>
                <ol class="indicator"></ol>
                <!-- The modal dialog, which will be used to wrap the lightbox content -->
                <div class="modal fade">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" aria-hidden="true">&times;</button>
                                <h4 class="modal-title"></h4>
                            </div>
                            <div class="modal-body next"></div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default pull-left prev">
                                    <i class="glyphicon glyphicon-chevron-left"></i>
                                    Previous
                                </button>
                                <button type="button" class="btn btn-primary next">
                                    Next
                                    <i class="glyphicon glyphicon-chevron-right"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>        


        </div>

    </div>

</div>
