<?php
$lics = $this->lics;
?>
<div class="jumbotron">
    <center><h2>Licitaciones</h2></center>
</div>
<div class="col-md-12" style="padding-left: 50px;padding-right: 50px;">
    <a class="btn btn-primary" href="<?php echo $this->url(array('controller' => 'tramites', 'action' => 'nueva-licitacion')); ?>" style="float: right;">Nueva Licitacion</a>
    <table class="table table-striped table-hover" id="tblicitaciones">
        <thead>
            <tr>
                <th>Tipo</th>
                <th>Hora</th>
                <th>Fecha</th>
                <th>Estado</th>
                <th>Motivo</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $l = new My\Entity\Licitacion();
            foreach ($lics as $l):
                ?>
                <tr id="<?php echo 'lic-' . $l->getId(); ?>">
                    <td width="100"><?php echo $l->getTipoDeContratacion(); ?></td>
                    <td width="50"><?php echo $l->getHoraDeApertura(); ?></td>
                    <td width="100"><?php echo $l->getFechaDeApertura(); ?></td>
                    <td width="75"><?php echo ($l->getActiva() == true) ? 'VIGENTE' : 'CADUCA' ?></td>

                    <td ><?php echo $l->getDescripcion(); ?></td>
                    <td width="150">
                        <a class="btn btn-primary btn-sm" href="<?php echo $this->url(array('controller' => 'tramites', 'action' => 'editar-licitacion', 'id' => $l->getId())) ?>">Editar</a>
                        <button class="btn btn-danger btn-sm" id="<?php echo 'boton-' . $l->getId(); ?>" onclick="eliminar(<?php echo $l->getId(); ?>)">Eliminar</button>
                    </td>
                </tr>
                <?php
            endforeach;
            ?>
        </tbody>
    </table>
</div>


<script type="text/javascript">
    
    $(document).ready(function () {
        $('#tblicitaciones').DataTable();
    });
    function eliminar(id) {
        var request = $.ajax({
            url: "http://localhost/paginamuni/public/administracion/tramites/eliminar-licitacion",
            method: "POST",
            data: {id: id},
            dataType: "html"
        });

        request.done(function (msg) {
            alert(msg);
            $("#lic-"+id).remove();
        });

        request.fail(function (jqXHR, textStatus) {
            alert("Request failed: " + textStatus);
        });
    }

    
</script>