<div class="imagen_principal_seccion_div">
    <img class="imagen_principal_seccion" src="<?php echo $this->baseUrl() . '/img/biblioteca_lavalle.jpg'; ?>">
    <div class="carousel-caption">
        <center><h1 style="font-size: 5em;">Biblioteca Pública</h1></center>
    </div>
</div>
<div class="contenedor seccion_ubicacion">
    <div id="descripsion-servicio" style="text-align: justify;margin-top: 50px;">

        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8" id="contenido_seccion">
                <strong>Coordinadora: Técnica y Profesora: LAURA BARRERA</strong><br>
                &nbsp;<br>
                <strong><em>Personal:</em></strong><br>
                &nbsp;
                <ul>
                    <li>Erika Mamancayo……. Auxiliar de Biblioteca</li>
                </ul>

                <ul>
                    <li>Estela Arancibia……. Auxiliar de Biblioteca</li>
                </ul>

                <ul>
                    <li>Carina González……. Auxiliar de Biblioteca</li>
                </ul>

                <ul>
                    <li>Tania Espirito……. Auxiliar de Biblioteca</li>
                </ul>

                <ul>
                    <li>Leticia Salazar……. Maestranza</li>
                </ul>
                &nbsp;<br>
                <strong><em>Misión:&nbsp;</em></strong><br>
                La función primordial de la unidad de información es ofrecer a TODOS los miembros de la comunidad, sin reparar en clases sociales y edades, los recursos necesarios para satisfacer sus necesidades en materia de información, formación, ocio y cultura.<br>
                De ésta manera la misión de la unidad de información es ampliar los horizontes, logrando una BIBLIOTECA ACTIVA para los ciudadanos del departamento.&nbsp;<br>
                &nbsp;<br>
                <strong><em>Servicios que brinda la institución:</em></strong>

                <ul>
                    <li>Talleres artísticos</li>
                    <li>Cursos de idiomas e informática</li>
                    <li>Consulta en sala para niños y adultos de bibliografía</li>
                    <li>Préstamo a domicilio de bibliografía</li>
                    <li>Actividades lúdicas y literarias para niños</li>
                    <li>Visita de escuelas del departamento</li>
                    <li>Proyecciones infantiles</li>
                    <li>Espacio para la tercera edad</li>
                    <li>Consulta de bibliografía online</li>
                    <li>Eventos y proyectos dirigidos a toda la comunidad</li>
                    <li>Digitalización de material bibliográfico</li>
                </ul>
                <br>
                <strong><em>&nbsp;Lugar de atención (Dirección):</em></strong>&nbsp;<br>
                &nbsp;<br>
                Calle Fleming 298 (Frente a parque Nativo)<br>
                <br>
                <strong><em>Días y Horarios de atención:</em></strong>&nbsp;<br>
                &nbsp;<br>
                De lunes a viernes de 08:00 a 20:00 horas<br>
                &nbsp;<br>
                <strong><em>Teléfonos de contacto:</em></strong><br>
                &nbsp;<br>
                261-5186327<br>
                261-4941089<br>
                &nbsp;<br>
                <br>
                <strong><em>Dirección de e-mail:</em></strong>&nbsp;<br>
                &nbsp;<br>
                bibliotecalavalle@gmail.com<br>
                &nbsp;<br>
                <strong><em>Dirección de Facebook:</em></strong>&nbsp;<br>
                &nbsp;<br>
                <a href="http://www.facebook.com/bibliotecapublicalavalle">www.facebook.com/bibliotecapublicalavalle</a><br>
                &nbsp;<br>
                <strong><em>Otros datos:</em></strong><br>
                &nbsp;<br>
                Para hacerse socio de la biblioteca debe:
                <ul style="list-style-type:circle">
                    <li>Completar la ficha de socio</li>
                    <li>Realizar un aporte para la biblioteca que puede ser:
                        <ul style="list-style-type:circle">
                            <li>Cuota por mes: $20</li>
                            <li>Un servicio a la biblioteca: puede ser digitalización de materiales impresos o colaboración en diferentes proyectos</li>
                            <li>Donación de Bibliografía</li>
                        </ul>
                    </li>
                </ul>
            </div>

            <div class="col-md-2"></div>
        </div>

    </div>
</div>
<script type="text/javascript">
$(window).ready(function (){ 
   $("#contenido_seccion > ul").addClass("list-group");
   $("#contenido_seccion > ul > li").addClass("list-group-item");
   $("#contenido_seccion > ul > li").addClass("list-group-item-info");
   $("#contenido_seccion > ul > li > ul").addClass("list-group");
   $("#contenido_seccion > ul > li > ul > li").addClass("list-group-item");
   $("#contenido_seccion > ul > li > ul > li").addClass("list-group-item-info");
});
</script>