<div class="imagen_principal_seccion_div">
    <img class="imagen_principal_seccion" src="<?php echo $this->baseUrl() . '/img/cdr_lavalle.jpg'; ?>">
    <div class="carousel-caption">
        <center><h1 style="font-size: 5em;">Centro de Documentación Rapida (C.D.R.)</h1></center>
    </div>
</div>
<div class="contenedor seccion_ubicacion">
    <div id="descripsion-servicio" style="text-align: justify;margin-top: 50px;">
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ut tortor ac lorem blandit volutpat a id augue. Vestibulum quis nunc ex. In sit amet vestibulum lorem, a viverra lectus. Maecenas sed libero semper, viverra neque tincidunt, egestas urna. Donec dapibus porttitor nisl, vitae tristique urna volutpat vitae. Mauris eleifend nisi arcu, eget cursus dolor fermentum at. Vestibulum nec dolor aliquet, rhoncus metus ut, pharetra mi. Suspendisse fermentum diam a augue posuere mollis. Cras pretium mauris in ipsum vulputate, et interdum nibh tempor. Donec imperdiet in leo sed porttitor. Sed vulputate ex a dui accumsan, ac suscipit ligula laoreet. Duis vitae blandit lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus gravida, erat sit amet porta accumsan, purus nunc commodo arcu, at venenatis turpis dui eget risus.
        </p>

        <p><strong style="line-height:1.6em">Dirección:&nbsp;<span style="line-height:1.6em">Dorrego 93</span></strong></p>

        <p><strong>Teléfono:<span style="line-height:1.6em">494-1332</span></strong></p>

        <p><strong>e-mail:&nbsp;<span style="line-height:1.6em">cdr.lavalle@hotmail.com</span></strong></p>

        <p><strong>Página Oficial: &nbsp;<span style="line-height:1.6em">http://www.mingobierno.mendoza.gov.ar/&nbsp;</span></strong></p>
    </div>
</div>