<div class="imagen_principal_seccion_div">
    <img class="imagen_principal_seccion" src="<?php echo $this->baseUrl() . '/img/cdr_lavalle.jpg'; ?>">
    <div class="carousel-caption">
        <center><h1 style="font-size: 5em;">Centro de Documentación Rápida (C.D.R.)</h1></center>
    </div>
</div>
<div class="contenedor seccion_ubicacion">
    <div id="descripsion-servicio" style="text-align: justify;margin-top: 50px;">
        

        <p><strong style="line-height:1.6em">Dirección:&nbsp;<span style="line-height:1.6em">Dorrego 93</span></strong></p>

        <p><strong>Teléfono:<span style="line-height:1.6em">494-1332</span></strong></p>

        <p><strong>E-mail:&nbsp;<span style="line-height:1.6em">cdr.lavalle@hotmail.com</span></strong></p>

        <p><strong>Página Oficial: &nbsp;<span style="line-height:1.6em">http://www.mingobierno.mendoza.gov.ar/&nbsp;</span></strong></p>
    </div>
</div>