<div class="imagen_principal_seccion_div">
    <img class="imagen_principal_seccion" src="<?php echo $this->baseUrl() . '/img/portada_con_logo.jpg'; ?>">
    <div class="carousel-caption">
        <center><h1 style="font-size: 5em;">Delegaciones Municipales</h1></center>

    </div>
</div>
<div class="contenedor seccion_ubicacion">
    <div id="descripsion-servicio" style="text-align: justify;margin-top: 50px;">
        <p><strong>Objetivos</strong></p>

        <ul>
            <li>Planificar, organizar, ejecutar los proyectos y servicios que brinda la Municipalidad en los distritos del departamento.</li>
            <li>Ser un vínculo entre la casa central de la Municipalidad y los vecinos de los distritos de Lavalle.</li>
        </ul>

        <p><strong>Funciones</strong></p>

        <ul>
            <li>Coordinar los diferentes servicios públicos que presta la Municipalidad en los distritos del departamento.</li>
            <li>Organizar, ejecutar y/o colaborar con las actividades educativas, sociales, deportivas, recreativas y culturales, entre otras, que se llevan a cabo los distritos de Lavalle.</li>
            <li>Llevar a cabo relevamientos de la situación social en los distritos de Lavalle.</li>
            <li>Organizar, articular y ejecutar proyectos y actividades con las áreas municipales en los distritos del departamento.</li>
        </ul>

        <div class="row" style="text-align: left;">
            <div class="col-md-4">
                <div class="panel panel-success">
                    <div class="panel-heading">Tres de Mayo</div>
                    <div class="panel-body">
                        <p><strong>Delegado: </strong>Sergio Rivera</p>
                        <p><strong>Direccion: </strong>Ruta Provincial 36 N°442</p>
                        <p><strong>Teléfono: </strong>0261-4909056</p>
                        <p><strong>E-mail: </strong>delegacióntresdemayo@hotmail.com.ar</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">

                <div class="panel panel-warning">
                    <div class="panel-heading">Jocoli</div>
                    <div class="panel-body">
                        <p><strong>Delegado: </strong>Manuel Conti</p>
                        <p><strong>Direccion: </strong>Ruta Provincial 36 N°442</p>
                        <p><strong>Teléfono: </strong> 0261-4905036</p>
                        <p><strong>E-mail: </strong>delegacionmunicipaljocoli@hotmail.com</p>
                    </div>
                </div>

            </div>
            <div class="col-md-4">

                <div class="panel panel-primary">
                    <div class="panel-heading">Alto del Olvido</div>
                    <div class="panel-body">
                        <p><strong>Delegado: </strong>Rubén Dallosta</p>
                        <p><strong>Direccion: </strong>Ruta Provincial 36 N°442</p>
                        <p><strong>Teléfono: </strong>261-6721872</p>
                        <p><strong>E-mail: </strong>delegacionaltodelolvido_lavalle@yahoo.com.ar</p>
                    </div>
                </div>

            </div>
        </div>

        
        ...
    </div>
</div>