<div class="imagen_principal_seccion_div">
    <img class="imagen_principal_seccion" src="<?php echo $this->baseUrl() . '/img/educacion_lavalle.jpg'; ?>">
    <div class="carousel-caption">
        <center><h1>Educación y Oferta educativa</h1></center>

    </div>
</div>
<div class="contenedor seccion_ubicacion">
    <div id="descripsion-servicio" style="text-align: justify;margin-top: 50px;">
        <!--<p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ut tortor ac lorem blandit volutpat a id augue. Vestibulum quis nunc ex. In sit amet vestibulum lorem, a viverra lectus. Maecenas sed libero semper, viverra neque tincidunt, egestas urna. Donec dapibus porttitor nisl, vitae tristique urna volutpat vitae. Mauris eleifend nisi arcu, eget cursus dolor fermentum at. Vestibulum nec dolor aliquet, rhoncus metus ut, pharetra mi. Suspendisse fermentum diam a augue posuere mollis. Cras pretium mauris in ipsum vulputate, et interdum nibh tempor. Donec imperdiet in leo sed porttitor. Sed vulputate ex a dui accumsan, ac suscipit ligula laoreet. Duis vitae blandit lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus gravida, erat sit amet porta accumsan, purus nunc commodo arcu, at venenatis turpis dui eget risus.
        </p>-->
    </div>

    <div class="row">

        <div class="panel panel-success">
            <div class="panel-heading">I.E.S. 9-024</div>
            <div class="panel-body">
                <p><strong>Domicilio: </strong>Doctor Moreno y Fleming. Lavalle. Mendoza</p>
                <p><strong>Telefono: </strong>261-4941958</p>
                <p><strong>Oferta Educativa: </strong></p>
                <ul style="margin-left: 20px;list-style: none;">
                    <li>Profesorado de Educación Especial con orientación en Discapacidad Intelectual (4 años).</li>
                    <li>Profesorado de Educación Secundaria en Lengua y Literatura (4 años).</li>
                    <li>Profesorado de Educación Secundaria en Matemática (4 años).</li>
                    <li>Tecnicatura Superior en Análisis y Programación de Sistemas (3 años).</li>
                    <li>Tecnicatura Superior en Enología e Industrias Frutihortícolas (3 años).</li>
                    <li>Tecnicatura Superior en Administración de Empresas (3 años).</li>
                    <li>Tecnicatura Superior en Gestión de los Recursos Hídricos (3 años).</li>
                    <li>Tecnicatura Superior en Higiene y Seguridad en el Trabajo (3 años) </li>
                    <li>Licenciatura en Tecnología Educativa (2 años)</li>
                </ul>
                
                <p><strong>Talleres y cursos:</strong></p>
                <ul style="margin-left: 20px;list-style: none;">
                    <li>Taller de música</li>
                    <li>Taller de teatro</li>
                    <li>Curso auxiliar en acompañamiento terapeutico</li>
                    <li>Curso de ingles</li>
                </ul>
                
                <p><strong>Postitulos:</strong></p>
                <ul style="margin-left: 20px;list-style: none;">
                    <li>Enseñanza de las Ciencias Sociales (primaria)</li>
                    <li>Enseñanza de las Ciencias Naturales (primaria)</li>
                    <li>Enseñanza de las Ciencias Naturales (secundaria)</li>
                </ul>
                
                <p><strong>Horarios de atencion: </strong> 8.30 a 13hrs y 14 a 22 hs.</p>
                <p><strong>E-mail:</strong> <a href="mailto:ies9024lavalle@yahoo.com.ar">ies9024_lavalle@yahoo.com.ar</a></p>
                <center><a class="btn btn-danger" href="http://ies9024.mza.infd.edu.ar/sitio/index.cgi">Pagina institucional</a></center>
            </div>
        </div>
        
        <div class="panel panel-warning">
            <div class="panel-heading">Instituto Nuestra Señora del Rosario</div>
            <div class="panel-body">
                <p><strong>Domicilio: </strong>Fray Luis Beltrán 192, Villa Tulumaya, Lavalle, Mendoza.</p>
                <p><strong>Telefono: </strong> 0261-4941414</p>
                <p><strong>Oferta Educativa: </strong></p>
                <ul style="margin-left: 20px;list-style: none;">
                    <li>Profesorado de Educación Primaria (4 años).</li>
                    <li>Profesorado de Educación Inicial (4 años).</li>
                </ul>
                <p><strong>Horarios de atencion: </strong> 15:00 a 21:00 hs.</p>
                <p><strong>E-mail:</strong> <a href="mailto:nsrosario@speedy.com.ar">nsrosario@speedy.com.ar</a></p>
                <center><a class="btn btn-danger" href="http://nsrosario.mza.infd.edu.ar/sitio/index.cgi">Pagina institucional</a></center>
            </div>
        </div>
    </div>
</div>
<s