<div class="contenedor">
    <br>
    <div class="panel panel-success">
        <div class="panel-heading">Centro de salud N° 1</div>
        <div class="panel-body">
            <p><strong>Domicilio: </strong>Calle Sarasa 123</p>
            <p><strong>Teléfono: </strong>4940001</p>
            <p><strong>Especialiades: </strong></p>
            <ul style="margin-left: 20px;list-style: none;">
                <li>Especialidad 1</li>
                <li>Especialidad 2</li>
                <li>Especialidad 3</li>
                <li>Especialidad 4</li>
            </ul>
            <p><strong>Horarios de atención: </strong>07:00 - 14:00 hs</p>
        </div>
    </div>
    <div class="panel panel-success">
        <div class="panel-heading">Centro de salud N° 2</div>
        <div class="panel-body">
            <p><strong>Domicilio: </strong>Calle Sarasa 456</p>
            <p><strong>Teléfono: </strong>4940002</p>
            <p><strong>Especialiades: </strong></p>
            <ul style="margin-left: 20px;list-style: none;">
                <li>Especialidad 1</li>
                <li>Especialidad 2</li>
                <li>Especialidad 3</li>
                <li>Especialidad 4</li>
            </ul>
            <p><strong>Horarios de atención: </strong>07:00 - 14:00 hs</p>
        </div>
    </div>

</div>


