<?php
header('Location: '.$this->url(array('controller'=>'index','action'=>'sitio-en-construccion')));
 ?>
<div class="imagen_principal_seccion_div">
    <img class="imagen_principal_seccion" src="<?php echo $this->baseUrl() . '/img/jardin_maternal_lavalle.jpg'; ?>">
    <div class="carousel-caption">
        <center><h1 style="font-size: 5em;">Jardines Maternales</h1></center>

    </div>
</div>
<div class="contenedor seccion_ubicacion">
    <div id="descripsion-servicio" style="text-align: justify;margin-top: 50px;">
        <p>
            Instituciones socio- educativas dedicadas a acompañar, guiar y atender a través de diferentes experiencias, el desarrollo integral del niño comprendido entre los 45 días a 3 años de edad. Además, contamos con Instituciones educativas y recreativas de origen social, abocadas a la atención de niños de 4 hasta los 14 años de edad.
        </p>

        <h2>Objetivos de estos Centros:</h2>

        <ul style="margin-left: 30px;">
            <li><span style="font-size:14px">Compartir con la familia la responsabilidad de la atención integral de los niños.</span></li>
            <li><span style="font-size:14px">Proteger el buen estado de salud de los mismos.</span></li>
            <li><span style="font-size:14px">Promover hábitos de alimentación e higiene.</span></li>
            <li><span style="font-size:14px">Contribuir a la satisfacción de las necesidades de afecto, respeto, identidad, seguridad e independencia.</span></li>
            <li><span style="font-size:14px">Brindar un adecuado ambiente físico, emocional, material para apuntalar el desarrollo madurativo.</span></li>
            <li><span style="font-size:14px">Favorecer el enriquecimiento del vínculo niño-familia-institución-comunidad.</span></li>
        </ul>

        <div class="row" style="text-align: left;">
            <div class="col-md-4">
                <div class="panel panel-success">
                    <div class="panel-heading">Jardín Maternal: 049</div>
                    <div class="panel-body">
                        <p><strong>Ubicación: </strong>Calle Remedios Escaladas - Polideportivo Municipal.</p>
                        <p><strong>Director: </strong>Ábrego Sandra</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">

                <div class="panel panel-warning">
                    <div class="panel-heading">Jardín Maternal: 050 Niño Jesús</div>
                    <div class="panel-body">
                        <p><strong>Ubicación: </strong>Calle Guardia s/n - Costa de Araujo.</p>
                        <p><strong>Director: </strong>Salem Carina</p>
                    </div>
                </div>

            </div>
            <div class="col-md-4">

                <div class="panel panel-primary">
                    <div class="panel-heading">Jardín Maternal: 050 Niño Jesús</div>
                    <div class="panel-body">
                        <p><strong>Ubicación: </strong>Calle Guardia s/n - Costa de Araujo.</p>
                        <p><strong>Director: </strong>Salem Carina</p>
                    </div>
                </div>

            </div>
        </div>
        
        <div class="row" style="text-align: left;">
            <div class="col-md-4">
                <div class="panel panel-success">
                    <div class="panel-heading">Jardín Maternal: 049</div>
                    <div class="panel-body">
                        <p><strong>Ubicación: </strong>Calle Remedios Escaladas - Polideportivo Municipal.</p>
                        <p><strong>Director: </strong>Ábrego Sandra</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">

                <div class="panel panel-warning">
                    <div class="panel-heading">Jardín Maternal: 050 Niño Jesús</div>
                    <div class="panel-body">
                        <p><strong>Ubicación: </strong>Calle Guardia s/n - Costa de Araujo.</p>
                        <p><strong>Director: </strong>Salem Carina</p>
                    </div>
                </div>

            </div>
            <div class="col-md-4">

                <div class="panel panel-primary">
                    <div class="panel-heading">Jardín Maternal: 050 Niño Jesús</div>
                    <div class="panel-body">
                        <p><strong>Ubicación: </strong>Calle Guardia s/n - Costa de Araujo.</p>
                        <p><strong>Director: </strong>Salem Carina</p>
                    </div>
                </div>

            </div>
        </div>
        ...
    </div>
</div>