<div class="contenido">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 col-sm-12">
            <table class="table tabla-telefonos">
                <tr>
                    <td><p><strong>Bomberos:</strong></p></td>
                    <td>4502582</td>
                </tr>
                <tr>
                    <td><p><strong>Policia:</strong></p></td>
                    <td>4502582</td>
                </tr>
                <tr>
                    <td><p><strong>Emergencias:</strong></p></td>
                    <td>4502582</td>
                </tr>
                <tr>
                    <td><p><strong>Proteccion Animal:</strong></p></td>
                    <td>4502582</td>
                </tr>
            </table>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>