<div class="imagen_principal_seccion_div">
    <img class="imagen_principal_seccion" src="<?php echo $this->baseUrl() . '/img/portada_con_logo.jpg'; ?>">
    <div class="carousel-caption">
        <center><h1 style="font-size: 5em;">Ventanilla Única</h1></center>

    </div>
</div>
<div class="contenedor seccion_ubicacion">
    <div id="descripsion-servicio" style="text-align: justify;margin-top: 50px;">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8" id="contenido_seccion">
                <p><strong>Principales Objetivos del Proyecto:</strong></p>

                <ul>
                    <li>Atender a los contribuyentes de manera dinámica, brindando un servicio integral, personalizado y eficiente, orientado a satisfacer las necesidades de los ciudadanos lavallinos.</li>
                    <li>Permitir el inicio de todo trámite municipal, sin necesidad de recibir información previa en otras áreas del municipio.</li>
                    <li>Facilitar el acceso a la información ampliando horarios de atención y cantidad de Recursos Humanos disponibles para que el ciudadano haga su consulta y/o trámite.</li>
                    <li>Lograr un ejercicio de gobierno más transparente, eficiente y cercano a la ciudadanía.</li>
                </ul>

                <p><br>
                    <strong>Especificaciones de Funcionamiento:</strong></p>

                <ul>
                    <li>La VU&nbsp;concentra y unifica la atención al público de las antiguas áreas de Mesa de Entradas, Recaudaciones, Apremios y Cementerio.</li>
                    <li><strong>Horario de Atención (Verano): de lunes a viernes de 7:30 a 13:30 hs.</strong></li>
                    <li>Incorporamos el circuito digital para trámites que recorren muchas oficinas.</li>
                    <li >Trámites que se pueden realizar:
                        <ol style="padding-left: 20px;">
                            <li><span style="font-size:14px">Consulta de deudas</span></li>
                            <li><span style="font-size:14px">Pago de deudas</span></li>
                            <li><span style="font-size:14px">Pago de tasas municipales o tasas por comercio</span></li>
                            <li><span style="font-size:14px">Contratación de servicio de tanque de agua y tanque atmosférico</span></li>
                            <li><span style="font-size:14px">Presentación de notas</span></li>
                            <li><span style="font-size:14px">Presentación de solicitudes/ reclamos/ sugerencias</span></li>
                            <li><span style="font-size:14px">Solicitud de conexión de luz/ agua/ gas</span></li>
                            <li><span style="font-size:14px">Solicitud de habilitación/ baja/ transferencia de comercio</span></li>
                            <li><span style="font-size:14px">Presentación de planos</span></li>
                            <li><span style="font-size:14px">Realización de trámites de cementerio</span></li>
                        </ol>
                    </li>
                </ul>



                <p>Para más información sobre cualquiera de estos trámites consulte la&nbsp;<strong><a href="http://mendozalavalle.com.ar/public/secciones/ver/id/14">guía de trámites web</a></strong>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(window).ready(function () {
        $("#contenido_seccion > ul").addClass("list-group");
        $("#contenido_seccion > ul > li").addClass("list-group-item");
        $("#contenido_seccion > ul > li").addClass("list-group-item-info");
        $("#contenido_seccion > ul > li > ul").addClass("list-group");
        $("#contenido_seccion > ul > li > ul > li").addClass("list-group-item");
        $("#contenido_seccion > ul > li > ul > li").addClass("list-group-item-info");
    });
</script>