<div class="imagen_principal_seccion_div">
    <img class="imagen_principal_seccion" src="<?php echo $this->baseUrl() . '/img/prom-economica.jpg'; ?>">
    <div class="carousel-caption">
        <center><h3>Desarrollo de Lavalle</h3></center>
        <p>
            El desarrollo económico del departamento de Lavalle se basa en su producción agropecuaria. De acuerdo a las condiciones del clima, este departamento presenta ventajosas e inmejorables posibilidades para desarrollar proyectos agrícolas exitosos.
            Las principales actividades agrícolas son:
        </p>
    </div>
</div>
<div class="contenedor seccion_ubicacion">
    <div class="row">
        <center>
            <h1>Económia</h1>
        </center>
        <h3>Formularios disponibles para descargar</h3>
        <div class="lista-descarga">
            <ul class="list-group">
                <li class="list-group-item">
                    <a class="link-descarga">Proyecto de inverción <span class="icono"><i class="fa fa-arrow-circle-down" aria-hidden="true"></i></span>
                    </a>
                </li>
                <li class="list-group-item">
                    <a class="link-descarga">Proyecto de inversión F° II<span class="icono"><i class="fa fa-arrow-circle-down" aria-hidden="true"></i></span>
                    </a>
                </li>
                <li class="list-group-item">
                    <a class="link-descarga">Guía de Solicitud de Terrenos Zona Industrial Lavalle<span class="icono"><i class="fa fa-arrow-circle-down" aria-hidden="true"></i></span>
                    </a>
                </li>
                <li class="list-group-item">
                    <a class="link-descarga">Nota Solicitud<span class="icono"><i class="fa fa-arrow-circle-down" aria-hidden="true"></i></span>
                    </a>
                </li>
                <li class="list-group-item">
                    <a class="link-descarga">Identificación de la Empresa<span class="icono"><i class="fa fa-arrow-circle-down" aria-hidden="true"></i></span>
                    </a>
                </li>
            </ul>
        </div>

        <div class="sectores-desarrollo">


            <div class="panel panel-info">
                <div class="panel-heading">
                    Vitivinicultura
                </div>
                <div class="panel-body">
                    <p>Es la actividad agrícola más importante del departamento. Un gran porcentaje de producción de uvas se destina a vinificación y otro a la elaboración de mostos, pasas y consumo en fresco.</p>
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">
                    Hidrocultura
                </div>
                <div class="panel-body">
                    <p>Se cultivan en el departamento de Lavalle, aproximadamente unas 3.300 hectáreas con especies hortícolas. Las que mejor se desarrollan son: ajo, cebolla, melón, sandía y tomate.</p>
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">
                    Fruticultura
                </div>
                <div class="panel-body">
                    <p>En los últimos años ha crecido notablemente, sobre todo las producciones de primicias. Las especies cultivadas más importantes y que mejor se adaptan son: ciruelos, peras, duraznos, membrillos, damascos.</p>
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">
                    Actividad Forestal
                </div>
                <div class="panel-body">
                    <p>El total de las tierras forestadas abarca unas 1.652 hectáreas, la principal especie, el álamo, se destina a la venta de madera, en menor medida a formar cortinas contra el viento en explotaciones agrícolas. La otra especie que le sigue en importancia es el eucalipto. En la zona desértica, se están llevando a cabo estudios, a fin de reforestar al mismo con especies autóctonas, como el algarrobo dulce.</p>
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">
                    Ganadería
                </div>
                <div class="panel-body">
                    <p>Se puede dividir en dos zonas ganaderas bien diferenciadas:</p>
                    <p><strong>Bajo Riego:</strong> productora de alfalfa de muy buena calidad, se adapta perfectamente al desarrollo de todo tipo de ganado, en especial el engorde de bovino y la cría de cerdos, entre otros.</p>
                    <p><strong>Secano:</strong> ocupa la mayor parte de la superficie del departamento. Es propicia para la cría de bovinos y principalmente de caprinos.</p>
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">
                    Apicultura
                </div>
                <div class="panel-body">
                    <p>Cuenta con dos zonas distintas para producir miel:</p>
                    <p><strong>Zona Desértica:</strong> dentro de este lugar encontramos asociaciones de ciertas especies vegetales, como el alpataco, el algarrobo, el atamisque, el chañar, etc., que convierten a las misma, en determinadas época del año, en un muy buena productora de polen y miel, de bajo contenido de humedad.</p>
                    <p><strong>Zona Irrigada:</strong> donde se cultivan viñedos, frutales, hortalizas, forestales y algunos forrajes. Las producción de polen en esta zona es muy interesante. La baja humedad relativa del departamento permite obtener un producto de alta calidad.</p>
                </div>
            </div>
        </div>

    </div>
</div>