<div class="contenedor seccion-galeria-principal">
    <div class="row seccion-galeria">

        <div class="col-md-12">

            <center>
                <?php
                $i = new My\Entity\Galeria();
                foreach ($this->imagenes as $i):
                    ?>
                    <a class="img-thumbnail" href="<?php echo $this->baseUrl() . '/img/galeria/' . $i->getUrl(); ?>" title="<?php echo $i->getTitulo(); ?>" data-gallery>
                        <img src="<?php echo $this->baseUrl() . '/img/galeria/thumbnails/' . $i->getUrl(); ?>">
                    </a>
                    <?php
                endforeach;
                ?>

            </center>
            <!-- The Gallery as lightbox dialog, should be a child element of the document body -->
            <div id="blueimp-gallery" class="blueimp-gallery">
                <!-- The container for the modal slides -->
                <div class="slides"></div>
                <!-- Controls for the borderless lightbox -->
                <h3 class="title"></h3>
                <a class="prev">‹</a>
                <a class="next">›</a>
                <a class="close">×</a>
                <a class="play-pause"></a>
                <ol class="indicator"></ol>
                <!-- The modal dialog, which will be used to wrap the lightbox content -->
                <div class="modal fade">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" aria-hidden="true">&times;</button>
                                <h4 class="modal-title"></h4>
                            </div>
                            <div class="modal-body next"></div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default pull-left prev">
                                    <i class="glyphicon glyphicon-chevron-left"></i>
                                    Previous
                                </button>
                                <button type="button" class="btn btn-primary next">
                                    Next
                                    <i class="glyphicon glyphicon-chevron-right"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>        


        </div>

    </div>
</div>