<!--<img class="imagen_principal_seccion" src="<?php //echo $this->baseUrl() . '/img/historia.jpg'; ?>">-->
<div class="contenedor seccion_historia">
    <div class="row">
        
        <center>
            <h1>Historia</h1></center>
        <p style="text-align: center;"><strong>CREACI&Oacute;N DEL DEPARTAMENTO</strong></p>

        <p style="text-align: justify;"><span style="font-size:13px; line-height:1.6em">El 18 de enero de 1859, el gobernador de la provincia don Cornelio Moyano firm&oacute; el decreto- ley por el que creaba el departamento de Tulumaya, en honor a la denominaci&oacute;n que los ind&iacute;genas del lugar daban a la regi&oacute;n.</span></p>

        <p style="text-align: justify;"><span style="font-size:13px; line-height:1.6em">En 1889 se cambi&oacute; su nombre por el de Lavalle, en homenaje al guerrero de la independencia.</span></p>

        <p style="text-align: justify;"><span style="font-size:13px; line-height:1.6em">El departamento celebra su aniversario haci&eacute;ndolo coincidir con el natalicio de su patrono civil, el General Juan Galo Lavalle, ocurrido el 20 de octubre de 1797.</span></p>

        <p>&nbsp;</p>


        <p style="text-align: center;"><strong>OR&Iacute;GENES DEL DEPARTAMENTO</strong></p>

        <p style="text-align: justify;">El departamento de Lavalle integr&oacute; originariamente la amplia zona de Huanacache, en cuya parte Norte estaban ubicadas las extensas lagunas del mismo nombre, formadas por los desag&uuml;es del r&iacute;o San Juan. En las proximidades de estas lagunas se encontraban radicados importantes y numerosos n&uacute;cleos de ind&iacute;genas huarpes, quienes se dedicaban a la pesca, confecci&oacute;n de canoas y canastos con totora y junquillo, as&iacute; como a otras peque&ntilde;as actividades de artesan&iacute;a. De esta zona, se tra&iacute;a el pescado, especialmente truchas, para el consumo de la poblaci&oacute;n de Mendoza.</p>

        <p style="text-align: justify;">Los ind&iacute;genas llamaban &ldquo;tulumaya&rdquo; o <strong><em>&ldquo;tule - mayu</em></strong>&rdquo;, a los territorios que hoy abarcan el departamento de Lavalle. Antes de la llegada de los espa&ntilde;oles, exist&iacute;an numerosas tolder&iacute;as, destac&aacute;ndose la de Jocoli, residencia del cacique Tabalqu&eacute;.</p>

        <p style="text-align: justify;">Los conquistadores espa&ntilde;oles tomaron posesi&oacute;n de las tierras del arroyo Tulumaya. El capit&aacute;n don Mart&iacute;n Pizarro de C&oacute;rdoba, recibi&oacute; en encomienda las comarcas que pertenec&iacute;an al cacique Guaquinchay. El capit&aacute;n general de Chile, don Domingo Ortiz de Rosas, tom&oacute; con entusiasmo la creaci&oacute;n de nuevos pueblos en la regi&oacute;n de Cuyo, especialmente en las lagunas de Huanacache. Nombr&oacute; como representante suyo a don Gregorio Blanco Laysequilla, quien en 1754 redact&oacute; un c&oacute;digo donde se establec&iacute;an&nbsp; las normas para crear nuevas poblaciones, como as&iacute; tambi&eacute;n el repartimiento de solares y tierras con destino al cultivo y crianza de hacienda.</p>

        <p style="text-align: justify;">Se supone que la primera &ldquo;doctrina&rdquo; de Huanacache data de 1601. En 1749 el misionero franciscano Marcos Videla hab&iacute;a logrado formar en las lagunas un pueblo de indios. Esta comunidad, constituye el nacimiento de las primeras poblaciones como Asunci&oacute;n, San Miguel y Rosario. En 1788 todas ellas fueron atacadas por los ind&iacute;genas, pero fueron rechazados y sometidos.</p>

        <p style="text-align: justify;">A fines del siglo XVIII, se establecieron en esta regi&oacute;n, algunos de los prisioneros portugueses, tomados por Pedro de Ceballos en su campa&ntilde;a de Santa Catalina. Los lusitanos se dedicaron a la pesca en las lagunas del Rosario y Huanacache. Seg&uacute;n el historiador Isidro J. Maza, &ldquo;esta actividad dio lugar al trazado de una senda o caminos que un&iacute;an las lagunas con la ciudad de Mendoza, por esta raz&oacute;n, dicha calle pas&oacute; a denominarse &ldquo;Los Pescadores&rdquo;.</p>

        <p style="text-align: justify;">En 1850 durante el gobierno de Alejo Mallea, la regi&oacute;n fue anexada al departamento de La paz. Pero cinco a&ntilde;os m&aacute;s tarde, el gobernador Pedro Pascual Segura la separ&oacute;, construyendo la Subdelagac&iacute;a del Rosario.</p>

    </div>
</div>

