<div class="imagen_principal_seccion_div">
    <img class="imagen_principal_seccion" src="<?php echo $this->baseUrl() . '/img/historia_lavalle_1.jpg'; ?>">
    <div class="carousel-caption">
        <center>
            <h1>Ubicación Geográfica</h1>
        </center>
        <p>
            Lavalle se encuentra al norte de la provincia de Mendoza. Sus límites son: al norte con la provincia de San Juan, al este con la provincia de San Luis, al oeste con el departamento de Las Heras y al sur con los departamentos de Santa Rosa, La Paz, San Martín, Maipú y Guaymallén. La superficie aproximada del departamento es de 10.242 km2. representando el 6,8 % de la superficie provincial.
        </p>
    </div>
</div>
<div class="contenedor seccion_ubicacion">
    <div class="row">


        <img class="img-responsive img-thumbnail" src="<?php echo $this->baseUrl() . '/img/distritos_lavalle.jpg'; ?>">

        <center>
            <div class="botones_ubicacion">
                <a class="btn btn-primary" href="<?php echo $this->baseUrl() ?>/pdf/mapas/Accesos a Lavalle pag web.pdf" onclick="window.open(this.href, this.target, 'width=700,height=600'); return false;" target="_blank">Accesos a Lavalle</a>
                <a class="btn btn-primary" href="<?php echo $this->baseUrl() ?>/pdf/mapas/Lavalle rutas y centros urbanos.pdf" onclick="window.open(this.href, this.target, 'width=700,height=600'); return false;" target="_blank">Rutas y centros urbanos</a>
                <a class="btn btn-primary" href="<?php echo $this->baseUrl() ?>/pdf/mapas/ingresosprincipales.pdf" onclick="window.open(this.href, this.target, 'width=700,height=600'); return false;" target="_blank">Ingresos principales</a>
            </div>
        </center>

        <div class="row candidatas">

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/alto_del_olvido.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Alto del Olvido</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/colonia_italia.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Colonia Italia</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/costa_de_araujo.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Costa de Araujo</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/el_carmen.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>El Carmen</h3></a>
                    </figcaption>
                </figure>
            </div>

        </div>

        <div class="row candidatas">


            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/el_chilcal.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>El Chilcal</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/el_plumero.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>El Plumero</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/el_vergel.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>El Vergel</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/gusavo_andre.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Gustavo André</h3></a>
                    </figcaption>
                </figure>
            </div>
        </div>

        <div class="row candidatas">


            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/jocoli.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Jocoli</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/jocoli_viejo.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Jocoli Viejo</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/la_asuncion.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>La Asuncion</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/la_bajada.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>La Bajada</h3></a>
                    </figcaption>
                </figure>
            </div>
        </div>

        <div class="row candidatas">


            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/la_holanda.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>La Holanda</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/la_palmera.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>La Palmera</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/la_pega.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>La Pega</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/lagunas_del_rosario.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Lagunas del Rosario</h3></a>
                    </figcaption>
                </figure>
            </div>
        </div>

        <div class="row candidatas">


            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/las_violetas.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Las Violetas</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/paramillo.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Paramillo</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/san_francisco.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>San Francisco</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/san_jose.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>San Jose</h3></a>
                    </figcaption>
                </figure>
            </div>
        </div>

        <div class="row candidatas">
            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/san_miguel.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>San Miguel</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/tres_de_mayo.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Tres de Mayo</h3></a>
                    </figcaption>
                </figure>
            </div>

            <div class="col-sm-6 col-departamento">
                <figure class="departamento">
                    <center><img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/villa_tulumaya.png' ?>" alt="..." class="img-departamento"></center>
                    <figcaption>
                        <a href="#" class="item-modal" data-toggle="modal" data-target="#myModal"><h3>Villa Tulumaya</h3></a>
                    </figcaption>
                </figure>
            </div>

        </div>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                    </div>
                    <div class="modal-body">
                        <center>
                            <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/alto_del_olvido.png' ?>" alt="..." class="img-circle img-candidata img-thumbnail">
                        </center>
                        <div class="descripcion_candidadta">
                            <h3>El Chilcal</h3>
                            <p><span>Nombre: </span>Camila Sol Morales</p>
                            <p><span>Edad: </span>21</p>
                            <p><span>Ojos: </span>Marrones</p>
                            <p><span>Cabello: </span>Castaño claro</p>
                            <p><span>Estudios: </span>Es estilista y cursará la carrera de periodismo</p>
                            <p><span>Hobby: </span>Pasar tiempo con amigos y ver obras de teatro</p>

                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
