<div class="imagen_principal_seccion_div">
    <img class="imagen_principal_seccion" src="<?php echo $this->baseUrl() . '/img/historia_lavalle_1.jpg'; ?>">
    <div id="portada_seccion" class="carousel-caption">
        <center>
            <h1>Ubicación Geográfica</h1>
        </center>
        <p>
            Lavalle se encuentra al norte de la provincia de Mendoza. Sus límites son: al norte, con la provincia de San Juan; al este, con la provincia de San Luis; al oeste, con el departamento de Las Heras y al sur, con los departamentos de Santa Rosa, La Paz, San Martín, Maipú y Guaymallén. La superficie aproximada del departamento es de 10.242 km2. representando el 6,8 % de la superficie provincial.
        </p>
    </div>
</div>
<div class="contenedor seccion_ubicacion">
    <div class="row">


        <img class="img-responsive img-thumbnail" src="<?php echo $this->baseUrl() . '/img/distritos_lavalle.jpg'; ?>">

        <center>
            <div class="botones_ubicacion">
                <a class="btn btn-primary" href="<?php echo $this->baseUrl() ?>/pdf/mapas/Accesos a Lavalle pag web.pdf" onclick="window.open(this.href, this.target, 'width=700,height=600'); return false;" target="_blank">Accesos a Lavalle</a>
                <a class="btn btn-primary" href="<?php echo $this->baseUrl() ?>/pdf/mapas/Lavalle rutas y centros urbanos.pdf" onclick="window.open(this.href, this.target, 'width=700,height=600'); return false;" target="_blank">Rutas y Centros Urbanos</a>
                <a class="btn btn-primary" href="<?php echo $this->baseUrl() ?>/pdf/mapas/ingresosprincipales.pdf" onclick="window.open(this.href, this.target, 'width=700,height=600'); return false;" target="_blank">Ingresos Principales</a>
            </div>
        </center>

        <div class="panel panel-success">
            <div class="panel-heading">El Chilcal</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/el_chilcal.png' ?>" style="float: right;" class="img-departamento">
                <p>Este distrito debe el nombre a la abundante existencia de plantas de Chilca, vegetación silvestre que crece en la zona.
                    El Chilcal, es un sector que ocupa un lugar especial en lo que hace a la caracterÍstica productiva de Lavalle. Sin lugar a dudas en mérito al tesón de su gente dedicada a la agricultura.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">El Plumero</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/el_plumero.png' ?>" style="float: right;" class="img-departamento">
                <p>Es el nombre que se le dio a una propiedad rural que era centro de actividades agrícolas y ganaderas en el departamento de Lavalle, y la origen de la aplicación de su nombre esta relacionado con “Plumerillo” osea lugar donde existen o existían plantas de cortaderas que dan un penacho blanco.
                </p>
            </div>
        </div>



        <div class="panel panel-success">
            <div class="panel-heading">El Vergel</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/el_vergel.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    Los primeros colonos lo llamaron El Vergel, que significa "huerto con diversidad de flores y árboles frutales". Así se convirtió en un lugar propicio donde se instalaron importantes emprendimientos agrícolas.
                    Este bello distrito que antiguamente destacaba por sus prósperos sembradíos y las frondosas arboledas está resurgiendo con la fuerza y perseverancia que sus primeros pobladores supieron transmitir a las nuevas generaciones.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">Gustavo André</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/gustavo_andre.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    Este distrito es una de las zonas del departamento que se caracteriza por su importante producción vitivinícola. Y en homenaje a los viñateros es que se realiza el Festival del Cosechador, evento que año a año reúne un numeroso público fanático de la música folclórica
                    FESTIVAL DEL COSECHADOR 19 y 20 de Marzo
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">Jocolí</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/jocoli.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    En el extremo de Lavalle, al noroeste del departamento está Jocolí, portal de acceso a nuestra provincia, pueblo de gente pujante que apuesta a diario por arraigarse en ese lugar. De acuerdo a la toponimia, el nombre Jocolí podría hacer referencia al vocablo aborigen Nogolí, que significa algarrobo, ya que en esta zona existían grandes algarrobales.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">Jocolí Viejo</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/jocoli_viejo.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    Este distrito situado a sólo unos 7 kilómetros al Oeste de la Villa cabecera, un lugar paulatino crecimiento, tanto por la producción de sus fincas, la instalación de centros de comercialización característicos productos de la zona, como ajos, melones, tomates y plantaciones olivícolas
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">La Bajada</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/la_bajada.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    Este pueblo está asentado a la vera del río Mendoza, probablemente de allí provenga su denominación haciendo referencia a la "bajada del río".
                    Esta zona, netamente rural, refleja en sus cultivos las manos laboriosas de hombres y mujeres que sol a sol trabajan por el crecimiento de este lugar.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">La Palmera</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/la_palmera.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    Su historia proviene de una planta de palmera que plantada en una propiedad rural, la misma servia para que la gente identificara el lugar y se guiara por aquella planta, es por esto que este distrito es reconocido y hoy lleva el nombre de La Palmera.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">La Pega</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/la_pega.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    Este distrito es uno de los portales de ingreso, ubicado al suroeste del departamento. Un pueblo de hombres y mujeres laboriosos que han forjado su futuro en este zona de viñedos y plantaciones hortícolas.
                    Según los pobladores más antiguos cuentan, que el camino que atraviesa este distrito, la actual ruta provincial n° 24, era una huella que cuando llovía era intransitable, por ese motivo las carretelas que quedaban pegadas en el fango y sus pasajeros debía esperar que se secara el terreno para continuar con el viaje.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">Lagunas del Rosario</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/lagunas_del_rosario.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    Capilla del Rosario, lleva dicho nombre desde las épocas en que los primeros doctrineros se establecieron en las Lagunas que pasaron a llamarse también del Rosario, en razón que la Capilla allí establecida fue dedicada a la veneración de Nuestra Señora del Rosario.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">Las Violetas</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/las_violetas.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    En este sector del Departamento, según relatos de los lugareños más antiguos, hacia fines del siglo XIX existía en la zona una propiedad rural donde la dueña de casa sembraba amplios jardines con plantas de violetas. Este hecho es el que identifica el lugar como Las Violetas.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">El Paramillo</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/paramillo.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    Este distrito formó parte hasta mediados de la década de los ’80 del distrito La Holanda, un sector de grandes extensiones de tierras pertenecientes a colonos holandeses, que por iniciativa de Cipriano Ibañez, primer intendente del departamento de Lavalle, de fines de siglo 19, los atrajo para que se afincaran en esas tierras.
                    Cuando la propia comunidad decide separarse de La Holanda, nombran a este nuevo distrito: Paramillo, tal como se llama la estación del ferrocarril Belgrano que existe en este lugar.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">San Francisco</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/san_francisco.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    En este sector del departamento se asentó una colonia de inmigrantes alemanes, liderados por Don Van Waveren, decididos a darle empuje a esta tierra. Hoy sus habitantes no abandonan este legado y reflejo de ello son sus extensas plantaciones de viñas y de productos hortícolas, como así también los emprendiminetos ganaderos que allí se instalan. Es también el límite Norte entre el oásis productivo y el Secano.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">San Miguel de los Sauces</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/san_miguel.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    En el extremo noreste de Lavalle está enclavado este amplio distrito del secano que alberga a cientos de familias de crianceros y artesanos en lana y junquillo, verdadero ejemplo de hombres de lucha y tesón que cada día vencen al tiempo.
                    Este pueblo también celebra uno de los festejos religiosos más antiguos del departamento, como las honras a San Miguel Arcángel en septiembre de cada año.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">Tres de Mayo</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/tres_de_mayo.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    Distrito ubicado en la ruta 36 de nuestro departamento. Los orígenes de este paraje cuenta que Don Elias Villanueva, afincado de este lugar organizaba la fiesta de su cumpleaños, quien convocaban a cientos de invitados de toda la provincia es por eso que este lugar era conocido por el “vamos para el Tres de Mayo”. 
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">Alto del Olvido</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/alto_del_olvido.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    Un lugar especial en la historia del Departamento representa este paraje. De acuerdo a la memoria oral de antiguos pobladores cuentan que el nombre de este lugar fue dado porque el servicio de transporte de pasajeros que existía por aquellos años, fines del siglo 19, también llamada La Mensajería olvidaba ingresar a este poblado.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">Villa Tulumaya</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/villa_tulumaya.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    Expresan los antecedentes de la toponimia lavallina, que la ciudad cabecera recibió dicho nombre de la voz quichua Tule Mayu. El primer término significa cortadera o junquillo y el segundo río, lo cual puede estar asociado al Arroyo Tulumaya que atraviesa este distrito. En este curso de agua que ha perdurado abundan las plantas de cortadera.
                    Este distrito también alberga válido potencial en producción, y en lo cultural no deja de ser un atractivo. Tiene sitios colmados de historia, como el Algarrobo Histórico, donde originalmente se asentó el centro de actividades de la Villa. Otro lugar de importancia es la antigua casona de la tradicional familia Montenegro, que hoy cobija el museo, donde se encuentra una diversidad de expresiones del pasado colonial del departamento.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">El Carmen</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/el_carmen.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    En este distrito, ubicado al noreste de Costa de Araujo, se popularizaron las honras a la patrona religiosa de la zona la Virgen del Carmen. Según cuentan los vecinos más antiguos se realizaba una procesión en honor a la virgen, la cual era portada en una carretilla por la calle principal.
                    Hasta este lugar convergían devotos para participar de las celebraciones de El Carmen, término que se afianzó para nombrar lo que se convertiría en ese distrito.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">Colonia Italia</div>
            <div class="panel-body">
                <img src="<?php echo $this->baseUrl() . '/img/mapas/departamentos/colonia_italia.png' ?>" style="float: right;" class="img-departamento">
                <p>
                    A principios de la creación de nuestro departamento llevaba el nombre de Colonia Italiana, debido a los primeros pobladores que habitaron esa zona, donde llegaron a trabajar y cultivar esa tierra.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">La Colmena</div>
            <div class="panel-body">

                <p>
                    Era el nombre de unas tierras que fueron de propiedad de don Juan Isidro Maza, que fuera gobernador de Mendoza hasta 1842 y a quien se le conocía como el "Caballero de Mendoza".
                    A estos extensos campos los antiguos lugareños le solían llamar los "campos Macinos" en razón al apellido de sus propietarios y al ser estos sub divididos entre sus herederos luego Doña Remedios Maza, que contrajo matrimonio con José Atahulfo Hoyos y en cuarta generación heredaron doña Magdalena de Hoyos Maza de Mathus y el Doctor Isidro Daniel Maza, este último que fuera diputado nacional por Mendoza y se encontraba casado con doña Enriqueta Granel.
                </p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">Oscar Mendoza</div>
            <div class="panel-body">
                <p>
                    Este paraje que se ubica en el extremo noroeste de la zona irrigada del departamento debe su nombre a uno de los fundadores del lugar, Don Oscar Mendoza. Un afincado que se asentó en la zona, transformándose en propietario de grandes parcelas de tierras, iniciando así en este lugar la actividad agrícola.
                </p>
            </div>
        </div>

    </div>



</div>
