<div class="contenedor">
    <div class="row">
    <?php 
    $areas = $this->areas;
    $a = new My\Entity\AreaMunicipal();
    foreach ($areas as $a) {
        ?>
        <div class="col-md-2 col-sm-4">
            <div class="anime">
                <div class="anime--flip">
                    <div class="anime--flip__flipper">
                        <div class="anime--flip__front">
                            <div clas="front">
                                <h3><?php echo $a->getTitulo(); ?></h3>
                            </div>
                        </div>
                        <div class="anime--flip__back">
                            <div class="back">
                                <p><?php echo 'A cargo de : '.$a->getAcargode(); ?></p>
                                <p>Dirección: <?php echo $a->getDireccion(); ?></p>
                                <p>Contacto: <?php echo $a->getTelefono(); ?></p>
                                <center><a href="#" class="btn btn-default btn-sm" data-toggle="modal" data-target="#modal-<?php echo $a->getId(); ?>">Ver mas</a></center>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php
    }
    ?>

        
    </div>
</div>



<!-- Modal -->
<?php 
    foreach ($areas as $a) {
        ?>
        <div class="modal fade" id="modal-<?php echo $a->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel"><?php echo $a->getTitulo(); ?></h4>
                    </div>
                    <div class="modal-body">
                            <p><strong>Director:</strong> <?php echo $a->getAcargode(); ?></p>
                            <p><strong>Dirección:</strong> <?php echo $a->getDireccion();?></p>
                            <p><strong>Contacto:</strong> <?php echo $a->getTelefono(); ?></p>
                        <div class="panel panel-primary">
                            <!-- Default panel contents -->
                            <div class="panel-heading">
                                Funciones
                            </div>

                            <!-- List group -->
                            <ul class="list-group">
                                <?php 
                                $lista = explode(";", $a->getFunciones());
                                foreach ($lista as $f) {
                                    ?>
                                    <li class="list-group-item"><?php echo $f; ?></li>
                                    <?php
                                }
                                ?>
                                
                            </ul>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
        <?php
    }
?>
