<div class="contenedor">
    <center>
        <div id="descripcion-asesoria" class="panel panel-default descripcion-asesoria">
            <div class="panel-heading">
                <center>
                    <h2>Asesor Legal: Dr. Hernán Pascual</h2>
                </center>
            </div>
            <div class="panel-body">
                <p><strong>Profesión:</strong> Abogado</p>
                <p><strong>Direccion:</strong> Planta alta de la casa central de la Municipalidad, calle Beltrán 37 de la ciudad cabecera de Lavalle.</p>
                <p><strong>Telefono:</strong> 261-4941573</p>
                <ul class="list-group">
                    <li class="list-group-item disabled">Objetivos</li>
                    <li class="list-group-item">Evaluar y asesorar jurídicamente a la municipalidad</li>
                    <li class="list-group-item">Realizar y analizar todo tipo de proyectos legales, contratos y/o convenios en los que interviene el municipio</li>
                </ul>

                <ul class="list-group">
                    <li class="list-group-item disabled">Funciones</li>
                    <li class="list-group-item">Emitir dictámenes jurídicos</li>
                    <li class="list-group-item">Actuar como apoderado jurídico de la comuna</li>
                    <li class="list-group-item">Elaborar y/o revisar los proyectos de contratos y convenios que celebra la municipalidad</li>
                    <li class="list-group-item">Formular y/o revisar proyectos de Ordenanzas, Decretos, Resoluciones o cualquier otra disposición que celebra el Municipio.</li>
                </ul>
            </div>
        </div>
    </center>
</div>