<div class="contenedor">
    <div class="contenedor-tab">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">H.C.D.</a></li>
            <li role="presentation"><a href="#tab-declaracion" aria-controls="tab-declaracion" role="tab" data-toggle="tab">Declaraciones</a></li>
            <li role="presentation"><a href="#tab-ordenanzas" aria-controls="tab-ordenanzas" role="tab" data-toggle="tab">Ordenanzas</a></li>
            <li role="presentation"><a href="#tab-resoluciones" aria-controls="tab-resoluciones" role="tab" data-toggle="tab">Resoluciones</a></li>
            <li role="presentation"><a href="#tab-ordenanzatarifaria" aria-controls="tab-ordenanzatarifaria" role="tab" data-toggle="tab">Ordenanza Tarifaria</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="home">
                <center>
                    <img class="img-responsive" src="<?php echo $this->baseUrl() . '/img/concejales.png'; ?>"/>
                </center>
            </div>
            <div role="tabpanel" class="tab-pane" id="tab-declaracion" style="height: 700px;overflow: scroll;">

                <?php
                $declaraciones = $this->declaraciones;
                $arch = new My\Entity\ProyectoHCD();
                foreach ($declaraciones as $arch){
                    ?>
                    <div class="media archivos-hcd">
                        <div class="media-left">
                            <a href="<?php echo $this->baseUrl().'/pdf/proyectohcd/'.$arch->getDocumento(); ?>" target="_blank">
                                <i class="fa fa-file-pdf-o fa-5x" aria-hidden="true"></i>
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading"><?php echo $arch->getTitulo(); ?></h4>
                            <p><?php echo $arch->getResumen(); ?></p>
                        </div>
                    </div>
                    <?php
                }
                ?>

            </div>
            <div role="tabpanel" class="tab-pane" id="tab-ordenanzas" style="height: 700px;overflow: scroll;">
                <?php
                foreach ($this->ordenanzas as $arch){
                    ?>
                    <div class="media archivos-hcd">
                        <div class="media-left">
                            <a href="<?php echo $this->baseUrl().'/pdf/proyectohcd/'.$arch->getDocumento(); ?>" target="_blank">
                                <i class="fa fa-file-pdf-o fa-5x" aria-hidden="true"></i>
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading"><?php echo $arch->getTitulo(); ?></h4>
                            <p><?php echo $arch->getResumen(); ?></p>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
            <div role="tabpanel" class="tab-pane" id="tab-resoluciones" style="height: 700px;overflow: scroll;">
                <?php
                foreach ($this->resoluciones as $arch){
                    ?>
                    <div class="media archivos-hcd">
                        <div class="media-left">
                            <a href="<?php echo $this->baseUrl().'/pdf/proyectohcd/'.$arch->getDocumento(); ?>" target="_blank">
                                <i class="fa fa-file-pdf-o fa-5x" aria-hidden="true"></i>
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading"><?php echo $arch->getTitulo(); ?></h4>
                            <p><?php echo $arch->getResumen(); ?></p>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
            <div role="tabpanel" class="tab-pane" id="tab-ordenanzatarifaria" style="height: 700px;overflow: scroll;">
                <?php
                foreach ($this->ordTarifarias as $arch){
                    ?>
                    <div class="media archivos-hcd">
                        <div class="media-left">
                            <a href="<?php echo $this->baseUrl().'/pdf/proyectohcd/'.$arch->getDocumento(); ?>" target="_blank">
                                <i class="fa fa-file-pdf-o fa-5x" aria-hidden="true"></i>
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading"><?php echo $arch->getTitulo(); ?></h4>
                            <p><?php echo $arch->getResumen(); ?></p>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>

    </div>
</div>