<div class="contenedor">
    <div class="imagen-perfil">
        <center><img class="img-thumbnail img-intendente" src="<?php echo $this->baseUrl() . '/img/ROBERTO-RIGHI.jpeg'; ?>"/></center>
    </div>

    <center>
        <div id="descripcion-intendente" class="panel panel-default descripcion-intendente">
            <div class="panel-heading">
                <center>
                    <h1>Roberto Righi</h1>
                </center>
            </div>
            <div class="panel-body">
                <p>Nació el día 21 de Octubre de 1972</p>
                <p><strong>Profesión:</strong> Técnico en Administración de Empresas y Comercialización.</p>
                <ul class="list-group">
                    <li class="list-group-item disabled">Formación</li>
                    <li class="list-group-item">Curso de Comercio Exterior (Chile)</li>
                    <li class="list-group-item">Jornada de Especialización sobre Desarrollo Rural, Ministerio de Desarrollo Social de la Nación.</li>
                    <li class="list-group-item">Participó en XXIV Programa Iberoamericano de Formación Municipal, realizado en la Ciudad de Madrid, España</li>
                </ul>
                
                <ul class="list-group">
                    <li class="list-group-item disabled">Cargos Públicos Anteriores</li>
                    <li class="list-group-item">Jefe de Turismo y Zonas no Irrigadas durante el período de 1995 a 1998</li>
                    <li class="list-group-item">Concejal electo desde el 23 abril de 1998 hasta el 21 de abril de 2002, con función de Presidente del Honorable Concejo Deliberante, quedando a cargo de la Intendencia Municipal desde el 07 de noviembre de 2001, hasta el 20 de noviembre de 2003.</li>
                    <li class="list-group-item">Intendente Municipal Electo desde el 21 de Noviembre de 2003 con periodo de cuatro años, conforme a la legislación vigente</li>
                    <li class="list-group-item">Intendente Municipal Electo desde el 28 de Octubre de 2007 con periodo de cuatro años, conforme a la legislación vigente</li>
                    <li class="list-group-item">Intendente Municipal Electo desde el 23 de Octubre de 2011 con periodo de cuatro años, conforme a la legislación vigente</li>
                </ul>
            </div>
        </div>
    </center>
</div>