<div class="contenedor">
    <div class="seccion-obras-publicas">
        <div class="row">
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="Acueducto del desierto" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">Acueducto del desierto</button>
            </div>
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="Gas Costa de Araujo" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">Gas Costa de Araujo</button>
            </div>
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="Gas El Chilcal – La Pega" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">Gas El Chilcal – La Pega</button>
            </div>
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="Gas Tres de Mayo y A. del Olvido" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">Gas Tres de Mayo y A. del Olvido</button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="Enripiado de Calles" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">Enripiado de Calles</button>
            </div>
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="CEIL" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">CEIL</button>
            </div>
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="Asfalto" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">Asfalto</button>
            </div>
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="Infraestructura para recreación y esparcimiento" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">Infraestructura para recreación y esparcimiento</button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3"><button class="btn btn-danger  btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="Adquisición de Equipos de Asfalto en Frío" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">Adquisición de Equipos de Asfalto en Frío</button>
            </div>
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="Asfaltos en Frío" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">Asfaltos en Frío</button>
            </div>
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="Red de Gas Gustavo André" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">Red de Gas Gustavo André</button>
            </div>
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="Red de Gas Jocolí Viejo y Jocolí" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">Red de Gas Jocolí Viejo y Jocolí</button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="Programa Construyendo Juntos" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">Programa Construyendo Juntos</button>
            </div>
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                          data-title="CIC Costa de Araujo y Jocolí" 
                                          data-content="
                                          <div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><strong>Descripción:</strong><ul><li>Sistema de Provisión de Agua a todas las localidades del desierto.</li></ul><strong>Dimensiones:</strong>
                                          <ol><li>300km de redes c/ estaciones de bombeo</li><li>Entrega de 600 tanques</li><li>2 Perforaciones</li></ol>Beneficia 600 familias
                                          <p>Inversion: $12.000.000</p><strong>Origen de los fondos:</strong><ul><li>$7.000.000 ENOHSA</li><li>$1.000.000 Otros entes Nacionales</li>
                                          <li>$4.000.000 Municipio</li></ul></div>">CIC Costa de Araujo y Jocolí</button>
            </div>
        </div>

        <hr>

        <div class="panel panel-default">
            <div class="panel-heading">
                <center><h2>Secretario: Ing. Rolando Romera</h2></center>
            </div>

            <div class="body descripcion_secretario">
                <div class="descripcion_secretario_detalle">
                    <p><strong>Profesión: </strong>Ingeniero industrial</p>
                    <p><strong>Mail: </strong>secobraspublicas@lavallemendoza.gov.ar</p>
                    <p><strong>Códigos públicos anteriores: </strong>Encargado de saneamiento de Ambiente, periodo del 2003 al 2012</p>
                </div>
                <center style="padding-bottom: 50px;"><h3>Direcciones a cargo de la secretaria de obras y servicios publicos</h3></center>

                <div class="row">
                    <div class="col-md-4">
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modalAmbiente">
                            Dirección de ambiente
                        </button>
                    </div>

                    <div class="col-md-4">

                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modalObrasPublicas">
                            Dirección de obras y servicios publicos
                        </button>
                    </div>

                    <div class="col-md-4">

                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modalVivienda">
                            Dirección de obras y servicios publicos
                        </button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- popups -->



<!-- Modal -->
<div class="modal fade" id="modalAmbiente" tabindex="-1" role="dialog" aria-labelledby="modalAmbiente">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Dirección de Ambiente</h4>
            </div>
            <div class="modal-body">
                <p><strong>Director: </strong>Pablo Termini</p>

                <p><strong>Profesión: </strong>Profesor de Cs. Naturales</p>

                <p>Cargos Públicos anteriores: </strong>Concejal de Lavalle, período del 2003 al 2007.</p>

                <p>Pres. Honorable Concejo Deliberante, en el año 2004.</p>

                <p><strong>Dirección: </strong>Polonio Montenegro y Pujadas</p>

                <p><strong>Tel: </strong>0261- 494 1402</p>

                <p><strong>e- mail: </strong>direccionambientelavalle@yahoo.com.ar</p>

                <p>Objetivos</p>
                <ul>
                    <li>Implementar políticas dirigidas a conservar el medio ambiente.</li>
                    <li>Abarcar el ámbito que representen la temática ambiental, mediante un proceso formativo de carácter abierto y permeable a los diferentes avances conceptuales y metodológicos.</li>
                    <li>Trasmitir conceptos destinados a fortalecer la conciencia ambiental en la sociedad.</li>
                    <li>Elaborar proyectos destinados a satisfacer a las necesidades ambientales del departamento.</li>
                    <li>Gestionar recursos propios o externos para ejecutar obras y/o proyectos especialmente referidos a temas ambientales.</li>
                </ul>
                <p>FUNCIONES</p>

                <p>Planificar las actividades a desarrollar por la Dirección. Adoptar una actividad comprometida con las necesidades ambientales del departamento a través de la elaboración de proyectos.</p>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal 2 -->
<div class="modal fade" id="modalObrasPublicas" tabindex="-1" role="dialog" aria-labelledby="modalObrasPublicas">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Dirección de Obras y Servicios Publicos</h4>
            </div>
            <div class="modal-body">
                <p><strong>Director: </strong>Julian Gallardo</p>
                <p><strong>Cargos publicos anteriores: </strong>Delegado Municipal de Gustavo André, período del año 1995 al 2006.</p>
                <p><strong>Dirección: </strong> Casa Central de la Municipalidad, ubicada en calle Beltrán 37 de la ciudad cabecera de Lavalle.</p>
                <p><strong>Teléfono: </strong>0261-494-1448</p>
                <p><strong>e-mail: </strong> obraspublicaslavalle@yahoo.com.ar</p>
                <p>Objetivos</p>
                <ul>
                    <li>Ejecutar obras públicas para mejorar la calidad de vida de los vecinos.</li>
                    <li>Proveer de diversos servicios públicos que la Municipalidad brinda a los vecinos del departamento.</li>
                    <li>Controlar la calidad de la obra privada en el departamento mediante las distintas secciones.</li>
                    <li>Controlas la calidad y cumplimiento de los servicios públicos prestados  por la Municipalidad</li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="modalVivienda" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Dirección de Vivienda</h4>
            </div>
            <div class="modal-body">
                <p><strong>Director: </strong>Jose Luis Blanco</p>
                <p><strong>Cargos publicos anteriores: </strong>Concejal de Lavalle.</p>
                <p><strong>Dirección: </strong> Casa central de la Municipal, ubicada en calle Beltrán 37 de la cuidad cabercera de Lavalle.</p>
                <p><strong>Teléfono: </strong>0261- 4941455</p>
                <p><strong>e-mail: </strong> viviendalavalle@yahoo.com.ar</p>
                <p>Objetivos</p>
                <ul>
                    <li>Brindar solución habitacional a los ciudadanos del departamento de Lavalle.</li>
                    <li>Urbanizar y equipar espacios destinados a complejos habitacionales.</li>
                </ul>
                
                <p>Función:</p>
                <ul>
                    <li>Atiende la demanda habitacional</li>
                    <li>Gestionar recursos en entes gubernamentales y no gubernamentales para la construcción, ampliación y terminación de viviendas, urbanización y equipamiento.</li>
                    <li>Acompaña en el desarrollo de los programas y la utilización de los recursos obtenidos.</li>
                    <li>Colaborar con la autogestión de las Entidades Intermedias que trabajan con el objetivos de construir viviendas.</li>
                    <li>Incrementar la mano de otras lavallinas en el rubro de la construcción mediante Cooperativas de trabajo.</li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover({
            html: true,
        });
    });

</script>