<div class="contenedor">
    <div class="seccion-obras-publicas">

        <?php 
        $obras = $this->obras;
        $o =  new My\Entity\Obra();
        $cont = 0;
        foreach ($obras as $o) {
          if ($cont % 4 == 0) {
            ?>
              <div class="row">
              <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                            data-title="<?php echo $o->getTitulo(); ?>" 
                                            data-content="<div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><?php echo $o->getContenido(); ?></div>"><?php echo $o->getTitulo(); ?></button>
              </div>
            <?php
          } else if (($cont + 1) % 4 == 0) {
            ?>
                <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                            data-title="<?php echo $o->getTitulo(); ?>" 
                                            data-content="<div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><?php echo $o->getContenido(); ?></div>"><?php echo $o->getTitulo(); ?></button>
              </div>
              </div>
            <?php
          } else {
            ?>
            <div class="col-md-3"><button class="btn btn-danger btn-obras" data-container="body" data-toggle="popover" data-placement="bottom"
                                            data-title="<?php echo $o->getTitulo(); ?>" 
                                            data-content="<div style='margin-left: 20px !important; margin-right:10px !important; margin-bottom:30px;'><?php echo $o->getContenido(); ?></div>"><?php echo $o->getTitulo(); ?></button>
              </div>
            <?php 
          }

          if($o === end($obras)){
            echo '</div>';
          }
          $cont++;
        }
        ?>
        

        <hr>

        <div class="panel panel-default">
            <div class="panel-heading">
                <center><h2>Secretario: Ing. Rolando Romera</h2></center>
            </div>

            <div class="body descripcion_secretario">
                <div class="descripcion_secretario_detalle">
                    <p><strong>Profesión: </strong>Ingeniero industrial</p>
                    <p><strong>Mail: </strong>secobraspublicas@lavallemendoza.gov.ar</p>
                    <p><strong>Códigos públicos anteriores: </strong>Encargado de saneamiento de Ambiente, periodo del 2003 al 2012</p>
                </div>
                <center style="padding-bottom: 50px;"><h3>Direcciones a Cargo de la Secretaría de Obras y Servicios Públicos</h3></center>

                <div class="row">

                  <?php 
                  $direcciones = $this->direcciones;
                  $d = new My\Entity\AreaMunicipal();
                  foreach ($direcciones as $d) {
                    ?>
                      <div class="col-md-4">
                          <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modal-<?php echo $d->getId(); ?>">
                              <?php echo $d->getTitulo(); ?>
                          </button>
                      </div>
                    <?php
                  }
                  ?>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- popups -->



<!-- Modal -->

<?php 
foreach ($direcciones as $d) {
?>
<div class="modal fade" id="modal-<?php echo $d->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="modalAmbiente">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><?php echo $d->getTitulo(); ?></h4>
            </div>
            <div class="modal-body" style="margin: 10px 30px;">
              <?php echo $d->getFunciones(); ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<?php
}
?>


<script type="text/javascript">
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover({
            html: true,
        });
    });

</script>