<div class="contendor-tramites">
    <center><h1>Guía de Trámites</h1></center>
    <div class="row">

        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title">
                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Conexión de Luz
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body">
                        <div class="tramite" id="tramiteluz">

                            <p>Requisitos</p>
                            <ul>
                                <li>Factibilidad de Servicios de EDEMSA</li>
                                <li>No tener deuda municipal (ni el inmueble ni el solicitante)</li>
                                <li>D.N.I. (titular de la propiedad)</li>
                                <li>Documentación de la Propiedad: Escritura - Contrato de Compra venta sellado por escribanía o D.G.R. o Certificado de residencia</li>
                            </ul>
                            <p>Casos Especiales</p>
                            <ul>
                                <li>Si es sucesión, firma del apoderado de la misma, con DNI y copia del Poder de sucesión.</li>
                                <li>Si el titular falleció puede firmar su cónyuge con fotocopia de acta de matrimonio y certificado de defunción.</li>
                                <li>En caso de Personas Jurídicas, debe firmar el presidente, y presentar fotocopia del estatuto, acta constitutiva y nómina de autoridades.</li>
                            </ul>
                            <p>Si la propiedad es alquilada</p>
                            <ul>
                                <li>o bien se deberá presentar el contrato de alquiler sellado y el locador debe ser el propietario del inmueble</li>
                                <li>o bien el propietario del inmueble con su DNI deberá firmar el formulario autorizado al solicitante a realizar el trámite</li>
                            </ul>
                            <p><strong>Costo: $230</strong></p>
                            <input type="button" class="btn btn-primary noImprimir" value="Imprimir" onclick="javascript:imprSelec('tramiteluz')">
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingTwo">
                    <h4 class="panel-title">
                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            Conexión de Agua o Cloacas
                        </a>
                    </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                    <div class="panel-body">
                        <div class="tramite" id="tramite-agua-cloacas">
                            Requisitos
                            <ul>
                                <li>Factibilidad de Servicios de AGUAS MENDOCINAS</li>
                                <li>No tener deuda municipal (ni el inmueble ni el solicitante)</li>
                                <li>D.N.I. (titular de la propiedad)</li>
                                <li>Documentación de la Propiedad: Escritura - Contrato de Compra venta sellado por escribanía o D.G.R. o Certificado de residencia</li>
                            </ul>
                            Casos Especiales

                            <ul>
                                <li>Si es sucesión, firma del apoderado de la misma, con DNI y copia del Poder de sucesión.</li>
                                <li>Si el titular falleció puede firmar su cónyuge con fotocopia de acta de matrimonio y certificado de defunción.</li>
                                <li>En caso de Personas Jurídicas, debe firmar el presidente, y presentar fotocopia del estatuto, acta constitutiva y nómina de autoridades.</li>
                            </ul>
                            Si la propiedad es alquilada

                            <ul>
                                <li>o bien se deberá presentar el contrato de alquiler sellado y el locador debe ser el propietario del inmueble</li>
                                <li>o bien el propietario del inmueble con su DNI deberá firmar el formulario autorizado al solicitante a realizar el trámite</li>
                            </ul>
                            <p><strong>Costo: $302</strong></p>
                            <input type="button" class="btn btn-primary noImprimir" value="Imprimir" onclick="javascript:imprSelec('tramite-agua-cloacas')">
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingThree">
                    <h4 class="panel-title">
                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            Conexión de Gas
                        </a>
                    </h4>
                </div>
                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                    <div class="panel-body">
                        <div class="tramite" id="tramite-gas">
                            Requisitos
                            <ul>
                                <li>No tener deuda municipal (ni el inmueble ni el solicitante)</li>
                                <li>D.N.I. (titular de la propiedad)</li>
                                <li>Documentación de la Propiedad: Escritura - Contrato de Compra venta sellado por escribanía o D.G.R. o Certificado de residencia</li>
                            </ul>
                            Casos Especiales

                            <ul>
                                <li>Si es sucesión, firma del apoderado de la misma, con DNI y copia del Poder de sucesión.</li>
                                <li>Si el titular falleció puede firmar su cónyuge con fotocopia de acta de matrimonio y certificado de defunción.</li>
                                <li>En caso de Personas Jurídicas, debe firmar el presidente, y presentar fotocopia del estatuto, acta constitutiva y nómina de autoridades.</li>
                            </ul>
                            <p><strong>Costo: $235</strong></p>
                            <input type="button" class="btn btn-primary noImprimir" 
                                   value="Imprimir" onclick="javascript:imprSelec('tramite-gas')">
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="cabecera4">
                    <h4 class="panel-title">
                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#cuerpo4" aria-expanded="false" aria-controls="cuerpo4">
                            Habilitación de Comercio
                        </a>
                    </h4>
                </div>
                <div id="cuerpo4" class="panel-collapse collapse" role="tabpanel" aria-labelledby="cabecera4">
                    <div class="panel-body">
                        <div class="tramite" id="tramite-hab-comercio">
                            Requisitos
                            <ul>
                                <li>No tener deuda municipal (ni el inmueble ni el solicitante)</li>
                                <li>fotocopia de D.N.I. del solicitante</li>
                                <li>Documentación de la Propiedad (en caso de no figurar como propietario en Catastro): Escritura - Contrato de Compra venta sellado por escribanía o D.G.R. o Certificado de residencia</li>
                            </ul>
                            Casos Especiales

                            <ul>
                                <li>Si es sucesión, firma del apoderado de la misma, con DNI y copia del Poder de sucesión.</li>
                                <li>Si el titular falleció puede firmar su cónyuge con fotocopia de acta de matrimonio y certificado de defunción.</li>
                                <li>En caso de Personas Jurídicas, debe firmar el presidente, y presentar fotocopia del estatuto, acta constitutiva y nómina de autoridades.</li>
                            </ul>
                            <p><strong>Costo: $210</strong></p>
                            <input type="button" class="btn btn-primary noImprimir" 
                                   value="Imprimir" onclick="javascript:imprSelec('tramite-hab-comercio')">
                        </div>
                    </div>
                </div>
            </div>



            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="cabecera5">
                    <h4 class="panel-title">
                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#cuerpo5" aria-expanded="false" aria-controls="cuerpo5">
                            Baja de Comercio
                        </a>
                    </h4>
                </div>
                <div id="cuerpo5" class="panel-collapse collapse" role="tabpanel" aria-labelledby="cabecera5">
                    <div class="panel-body">
                        <div class="tramite" id="tramite-baja-comercio">
                            Requisitos
                            <ul>
                                <li>No tener deuda municipal (ni el inmueble ni el solicitante)</li>
                                <li>fotocopia de D.N.I. del solicitante</li>
                            </ul>
                            <p><strong>Costo: $140</strong></p>
                            <input type="button" class="btn btn-primary noImprimir" 
                                   value="Imprimir" onclick="javascript:imprSelec('tramite-baja-comercio')">
                        </div>
                    </div>
                </div>
            </div>


            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="cabecera6">
                    <h4 class="panel-title">
                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#cuerpo6" aria-expanded="false" aria-controls="cuerpo6">
                            Transferencía de Comercio
                        </a>
                    </h4>
                </div>
                <div id="cuerpo6" class="panel-collapse collapse" role="tabpanel" aria-labelledby="cabecera6">
                    <div class="panel-body">

                        <div class="tramite" id="tramite-tranf-com">
                            Requisitos
                            <ul>
                                <li>No tener deuda municipal (ni el inmueble ni el solicitante)</li>
                                <li>fotocopia de D.N.I. del vendedor y del comprador</li>
                                <li>Documentación de la Propiedad (en caso de no figurar como propietario en Catastro): Escritura - Contrato de Compra venta sellado por escribanía o D.G.R. o Certificado de residencia</li>
                            </ul>
                            Casos Especiales

                            <ul>
                                <li>Si es sucesión, firma del apoderado de la misma, con DNI y copia del Poder de sucesión.</li>
                                <li>Si el titular falleció puede firmar su cónyuge con fotocopia de acta de matrimonio y certificado de defunción.</li>
                                <li>En caso de Personas Jurídicas, debe firmar el presidente, y presentar fotocopia del estatuto, acta constitutiva y nómina de autoridades.</li>
                            </ul>
                            Si la propiedad es alquilada

                            <ul>
                                <li>o bien se deberá presentar el contrato de alquiler sellado y el locador debe ser el propietario del inmueble</li>
                                <li>o bien el propietario del inmueble con su DNI deberá firmar el formulario autorizado al solicitante a realizar el trámite</li>
                            </ul>
                            <p><strong>Costo: $110</strong></p>
                            <input type="button" class="btn btn-primary noImprimir" 
                                   value="Imprimir" onclick="javascript:imprSelec('tramite-tranf-com')">
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="cabecera7">
                    <h4 class="panel-title">
                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#cuerpo7" aria-expanded="false" aria-controls="cuerpo7">
                            Presentación de Planos
                        </a>
                    </h4>
                </div>
                <div id="cuerpo7" class="panel-collapse collapse" role="tabpanel" aria-labelledby="cabecera7">
                    <div class="panel-body">
                        <div class="tramite" id="tramite-pres-plan">
                            Requisitos
                            <ul>
                                <li>Formulario extendido por Obras y Servicios Públicos (Completo c/aforos)</li>
                                <li>El formulario y planos deben estar firmados por el propietario y el Técnico.</li>
                                <li>No tener deuda municipal (inmueble).</li>
                                <li>Documentación de la Propiedad: Escritura - Contrato de Compra venta sellado por escribanía o D.G.R.</li>
                                <li>Certificado de profesional de la obra extendido por el Colegio de Arquitectos de Mendoza. </li>

                            </ul>
                            Casos Especiales

                            <ul>
                                <li>Si es sucesión firma el apoderado de la misma, con DNI y copia del Poder de sucesión.</li>
                                <li>En caso de hacer la presentación la firma constructora, debe presentar el firmante apoderado la documentación donde consta la autorización de la empresa p/realizar trámites.</li>
                            </ul>
                            <p>Costo: $165 (en caso de presentar 01 plano original y 01 duplicado, valor plano original: $112 c/u, valor plano duplicado: $75c/u).-</p>
                            <input type="button" class="btn btn-primary noImprimir" 
                                   value="Imprimir" onclick="javascript:imprSelec('tramite-pres-plan')">
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="cabecera8">
                    <h4 class="panel-title">
                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#cuerpo8" aria-expanded="false" aria-controls="cuerpo8">
                            Transferencia de Inmuebles
                        </a>
                    </h4>
                </div>
                <div id="cuerpo8" class="panel-collapse collapse" role="tabpanel" aria-labelledby="cabecera8">
                    <div class="panel-body">
                        <div class="tramite" id="tramite-tran-inmu">
                            Requisitos
                            <ul>
                                <li>Boleto de transferencia (por duplicado)</li>
                                <li>Copia de la Matricula.</li>
                                <li>Copia del Certificado Catastral.</li>
                                <li>Plano de Mensura.</li>
                                <li>Declaración Jurada de Construcciones.</li>
                                <li>Libre de Deuda Municipal en cualquier concepto.</li>
                            </ul>
                            <p><strong>Costo: $400</strong></p>
                            <input type="button" class="btn btn-primary noImprimir" 
                                   value="Imprimir" onclick="javascript:imprSelec('tramite-tran-inmu')">
                            <a class="btn btn-primary" href="<?php echo $this->baseUrl() . '/docs/FORMULARIO TRANSFERENCIA INMUEBLES.doc' ?>" target="_blank" onclick="window.open(this.href, this.target, 'width=700,height=600');return = false;" role="button" data-toggle="modal">Descargar Formulario</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script language="Javascript">
    function imprSelec(nombre) {
        var ficha = document.getElementById(nombre);
        var ventimp = window.open(' ', 'popimpr');
        ventimp.document.write(ficha.innerHTML);
        ventimp.document.close();
        ventimp.print( );
        ventimp.close();
    }
</script>
