<div class="jumbotron">
    <center>
        <h2>Archivos del HCD</h2>
    </center>
</div>
<div style="display: flex;justify-content: center; align-items: center;">
    <div class="col-md-8">
        <a class="btn btn-info" style="float: right;" href="<?php echo $this->url(array('controller' => 'gobierno', 'action' => 'nuevo-documento-consejo')); ?>">Neuva Area</a>
        <table class="table table-hover table-striped" id="example">
            <thead>
                <tr>
                    <th>Tipo</th>
                    <th>Titulo</th>
                    <th>Resumen</th>
                    <th>Url</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $a = new My\Entity\ProyectoHCD();
                foreach ($this->archivos as $a):
                    ?>
                <tr>
                    <td><?php echo $a->getTipo(); ?></td>
                    <td><?php echo $a->getTitulo(); ?></td>
                    <td><?php echo $a->getResumen(); ?></td>
                    <td><?php echo $a->getDocumento(); ?></td>
                    <td>
                            <a class="btn btn-success btn-sm" href="<?php echo $this->url(array('controller' => 'gobierno', 'action' => 'editar-documento-consejo', 'id' => $a->getId())); ?>">Editar</a>
                            <a class="btn btn-danger btn-sm" href="<?php echo $this->url(array('controller' => 'gobierno', 'action' => 'borrar-documento-consejo', 'id' => $a->getId())); ?>">Eliminar</a>
                    </td>
                </tr>
                <?php
                endforeach;
                ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>