<?php
$areas = $this->areas;
?>
<div class="jumbotron">
    <center>
        <h1>Areas Municipales</h1>
    </center>
</div>

<div id="div-padre" style="display: flex;justify-content: center;align-items: center;">
    <div id="div-hijo" style="width: 700px;">
        <a class="btn btn-info" style="float: right;" href="<?php echo $this->url(array('controller' => 'gobierno', 'action' => 'nueva-area')); ?>">Neuva Area</a>
        <table class="table table-hover table-striped table-responsive">
            <thead>
                <tr>
                    <th>Titulo</th>
                    <th>A cargo de</th>
                    <th>Cargo anterior</th>
                    <th>Dirección</th>
                    <th>Telefonos</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $a = new My\Entity\AreaMunicipal();
                foreach ($areas as $a):
                    ?>
                    <tr>
                        <td><?php echo $a->getTitulo(); ?></td>
                        <td><?php echo $a->getAcargode(); ?></td>
                        <td><?php echo $a->getCargoanterior(); ?></td>
                        <td><?php echo $a->getDireccion(); ?></td>
                        <td><?php echo $a->getTelefono(); ?></td>
                        <td>
                            <a class="btn btn-success btn-sm" href="<?php echo $this->url(array('controller' => 'gobierno', 'action' => 'editar-area', 'id' => $a->getId())); ?>">Editar</a>
                            <a class="btn btn-danger btn-sm" href="<?php echo $this->url(array('controller' => 'turismo', 'action' => 'eliminar-area', 'id' => $a->getId())); ?>">Eliminar</a>
                        </td>
                    </tr>  
                    <?php
                endforeach;
                ?>
            </tbody>
        </table>
    </div>
</div>