<div class="jumbotron">
    <center>
        <h1>Gobierno</h1>
    </center>
</div>
<center>
    <a href="<?php echo $this->url(array('controller'=>'gobierno','action'=>'areas-municipales'));?>" class="btn btn-default">Areas Municipales</a>
    <a href="<?php echo $this->url(array('controller'=>'gobierno','action'=>'secretaria-obras-servicios-publicos'));?>" class="btn btn-default">Secretaria Ogras y Servicios Publicos</a>
    <a href="<?php echo $this->url(array('controller'=>'gobierno','action'=>'archivos-consejo'));?>" class="btn btn-default">Consejo</a>
</center>