
<ul class="nav navbar-nav">
    <li><a href="<?php echo $this->url(array('controller'=>'departamento','action'=>'historia')); ?>">Historia</a></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Ubicacion Geografica <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="<?php echo $this->url(array('controller'=>'departamento','action'=>'distritos')); ?>">Departamentos</a></li>
            <li><a href="#">Archivos</a></li>
            <li><a href="#">Seccion</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Economia <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="#">Formularios</a></li>
            <li><a href="#">Aspectos economicos</a>
        </ul>
    </li>
</ul>

<div class="jumbotron">
    <center><h1>Departamento</h1></center>
</div>