<?php
header('Location: '.$this->url(array('controller'=>'index','action'=>'sitio-en-construccion')));
 ?>

<!--<div class="contenedor">
    <br>
    <div class="panel panel-success">
        <div class="panel-heading">01-01-2017 01:00:00</div>
        <div class="panel-body">
            <h4 class="media-heading">Middle aligned media</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in urna nec felis vehicula varius ac vel urna. Integer suscipit sapien tortor, non hendrerit elit ultricies a. Nullam congue lectus vel suscipit scelerisque. Mauris euismod sapien eget mauris finibus, ac sollicitudin diam porttitor. Nunc cursus ipsum enim, faucibus accumsan diam aliquet vitae. Vivamus a fermentum leo, eu sagittis felis. Donec malesuada urna eu purus sagittis tincidunt. Sed rhoncus mollis vehicula. Ut ornare ex in ex euismod varius. Donec pulvinar pretium eleifend.
            </p>
            <p>
                Quisque vitae vulputate risus. Ut aliquam erat quam, eu tincidunt lorem viverra sed. Nulla maximus ut dui id pretium. Nulla quis mi metus. Donec consequat sed ipsum vitae congue. Curabitur pulvinar enim eu mi tempor congue. Fusce euismod luctus tincidunt. Nulla facilisi.
            </p>

        </div>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">01-01-2017 12:00:00</div>
        <div class="panel-body">
            <h4 class="media-heading">Middle aligned media</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in urna nec felis vehicula varius ac vel urna. Integer suscipit sapien tortor, non hendrerit elit ultricies a. Nullam congue lectus vel suscipit scelerisque. Mauris euismod sapien eget mauris finibus, ac sollicitudin diam porttitor. Nunc cursus ipsum enim, faucibus accumsan diam aliquet vitae. Vivamus a fermentum leo, eu sagittis felis. Donec malesuada urna eu purus sagittis tincidunt. Sed rhoncus mollis vehicula. Ut ornare ex in ex euismod varius. Donec pulvinar pretium eleifend.
            </p>
            <p>
                Quisque vitae vulputate risus. Ut aliquam erat quam, eu tincidunt lorem viverra sed. Nulla maximus ut dui id pretium. Nulla quis mi metus. Donec consequat sed ipsum vitae congue. Curabitur pulvinar enim eu mi tempor congue. Fusce euismod luctus tincidunt. Nulla facilisi.
            </p>

        </div>
    </div>

    <div class="panel panel-warning">
        <div class="panel-heading">01-01-2017 21:00:00</div>
        <div class="panel-body">
            <h4 class="media-heading">Middle aligned media</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in urna nec felis vehicula varius ac vel urna. Integer suscipit sapien tortor, non hendrerit elit ultricies a. Nullam congue lectus vel suscipit scelerisque. Mauris euismod sapien eget mauris finibus, ac sollicitudin diam porttitor. Nunc cursus ipsum enim, faucibus accumsan diam aliquet vitae. Vivamus a fermentum leo, eu sagittis felis. Donec malesuada urna eu purus sagittis tincidunt. Sed rhoncus mollis vehicula. Ut ornare ex in ex euismod varius. Donec pulvinar pretium eleifend.
            </p>
            <p>
                Quisque vitae vulputate risus. Ut aliquam erat quam, eu tincidunt lorem viverra sed. Nulla maximus ut dui id pretium. Nulla quis mi metus. Donec consequat sed ipsum vitae congue. Curabitur pulvinar enim eu mi tempor congue. Fusce euismod luctus tincidunt. Nulla facilisi.
            </p>

        </div>
    </div>

</div>-->