<div class="contenedor contenido-alojamiento">

    <?php
    $alojamientos = $this->alojamiento;
    $s = new My\Entity\Sitios();
    $cont = 0;
    foreach ($alojamientos as $s):
        if ($cont % 4 == 0) {
            ?>
            <div class="row">
                <div class="col-md-3">
                    <button type="button" id="btn-<?php echo $s->getId(); ?>" class="btn btn-primary" data-toggle="modal" data-target="#modal-<?php echo $s->getId(); ?>"><i class="fa fa-bed fa-2x" aria-hidden="true"> </i> <?php echo $s->getTitulo(); ?></button>
                </div>
                <?php
            } else if (($cont + 1) % 4 == 0) {
                ?>
                <div class="col-md-3">
                    <button type="button" id="btn-<?php echo $s->getId(); ?>" class="btn btn-primary" data-toggle="modal" data-target="#modal-<?php echo $s->getId(); ?>"><i class="fa fa-bed fa-2x" aria-hidden="true"> </i> <?php echo $s->getTitulo(); ?></button>
                </div>
            </div>
            <?php
        } else {
            ?>
            <div class="col-md-3">
                <button type="button" id="btn-<?php echo $s->getId(); ?>" class="btn btn-primary" data-toggle="modal" data-target="#modal-<?php echo $s->getId(); ?>"><i class="fa fa-bed fa-2x" aria-hidden="true"> </i> <?php echo $s->getTitulo(); ?></button>
            </div>
            <?php
            if($s === end($alojamientos)){
                echo '</div>';
            }
        }
        $cont++;
    endforeach;
    ?>

    
</div>


<?php
foreach ($alojamientos as $s):
    ?>
<div class="modal fade" id="modal-<?php echo $s->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel"><?php echo $s->getTitulo(); ?></h4>
                </div>
                <div class="modal-body">
                    <?php
                    $imagenes = $s->getImagenes();
                    $i = new My\Entity\Imagen();

                    if (sizeof($imagenes) > 1) {
                        ?>
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">


                            <!-- Wrapper for slides -->
                            <div class="carousel-inner" role="listbox">

                                <?php
                                $cont = 0;
                                foreach ($imagenes as $i) {

                                    if ($cont == 0) {
                                        ?>
                                        <div class="item active">
                                            <center><img src="<?php echo $this->baseUrl() . '/img/turismo/sitios/' . $i->getUrl(); ?>" alt="" class="imagenes-carousel"></center>
                                        </div>
                                        <?php
                                        $cont++;
                                    } else {
                                        ?>
                                        <div class="item">
                                            <center><img src="<?php echo $this->baseUrl() . '/img/turismo/sitios/' . $i->getUrl(); ?>" alt="" class="imagenes-carousel"></center>
                                        </div>
                                        <?php
                                    }
                                }
                                ?>

                            </div>

                            <!-- Controls -->
                            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            </a>
                        </div>
                        <?php
                    } else if (sizeof($imagenes) == 1) {
                        //ingresara solo una vez
                        foreach ($imagenes as $i) {
                            ?>
                            <center><img src="<?php echo $this->baseUrl() . '/img/turismo/sitios/' . $i->getUrl(); ?>"></center>
                            <?php
                        }
                    }
                    ?>

                    <br>
                    <div style="margin-left: 20px;"><?php echo $s->getContenido(); ?></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    <?php
endforeach;
?>
