<div class="contenedor contenido-contacto-informes">
    <center><h1>Contacto e Informes</h1></center>

    <p>
        <strong>Direccion de cultura, turismo y deporte:</strong>
    </p>
    <p>
        <strong>Domicilio: </strong>Dr. Moreno y Calle Fleming - Villa Tulumaya - Casa de la historia y la cultura
    </p>
    <p>
        <strong>Teléfono: </strong>0261-4941147
    </p>
    <p>
        <strong>E-mail: </strong>lavalle_turismo@hotmail.com, turismoyculturalavalle@yahoo.com.ar
    </p>
    <center>
        <iframe style="margin-bottom: 50px;" class="thumbnail" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2822.6124678379283!2d-68.60042190387698!3d-32.721373571388455!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x887675d3d5467270!2sCasa+de+la+Cultura+Juanita+Vera!5e0!3m2!1ses-419!2sar!4v1480424952283" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </center>
</div>