<div class="contenedor contenido-gastronomia">
    <div class="row">
        <div class="col-md-3">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-cutlery fa-2x" aria-hidden="true"> </i> Puesto Díaz</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-cutlery fa-2x" aria-hidden="true"> </i> Puesto el Águila</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-cutlery fa-2x" aria-hidden="true"> </i> Puesto Los Hermanos Gonzáles</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-cutlery fa-2x" aria-hidden="true"> </i> Las 3F</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-cutlery fa-2x" aria-hidden="true"> </i> Las Marujitas Changlot</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-cutlery fa-2x" aria-hidden="true"> </i> Puesto El Algarrobo</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-cutlery fa-2x" aria-hidden="true"> </i> "BET - EL" portal de Mendoza</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-cutlery fa-2x" aria-hidden="true"> </i> El Baquiano</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-cutlery fa-2x" aria-hidden="true"> </i> Sadiki</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-cutlery fa-2x" aria-hidden="true"> </i> Tango Resto Bar</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-cutlery fa-2x" aria-hidden="true"> </i> Panadería y cafetería Marisa</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-cutlery fa-2x" aria-hidden="true"> </i> Donde Era La Villa</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal"><i class="fa fa-cutlery fa-2x" aria-hidden="true"> </i> La Gringa Resto Bar</button>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">

                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    </ol>
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <center><img src="http://lavallemendoza.gob.ar/img/botonerass/Puesto%20El%20Algarrobo...jpg"></center>
                        </div>
                        <div class="item">
                            <center><img src="http://lavallemendoza.gob.ar/img/botonerass/El%20algarrobo.jpg"></center>
                        </div>
                    </div>

                </div>
                <div class="datos-alojamiento">
                    <ul>
                        <li>Ubicación: Pueblo de La Asunción</li>
                        <li>Teléfono: 0261-155727044</li>
                    </ul>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>