<div class="contenedor botones-sitios">
    <div class="row">
        <div class="col-md-1 col-sm-6">
            <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#modal-museo">Museo</button>
        </div>
        <div class="col-md-3 col-sm-6">
            <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#modal-reserva">Reserva Telteca y Altos Limpios</button>
        </div>
        <div class="col-md-2 col-sm-6">
            <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#modal-tecta">Tecta Ti Cuyum</button>
        </div>
        <div class="col-md-2 col-sm-6">
            <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#modal-abuelo">Finca Abuelo Juan</button>
        </div>
        <div class="col-md-2 col-sm-6">
            <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#modal-cosmos">Cosmos</button>
        </div>
        <div class="col-md-2 col-sm-6">
            <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#modal-alma">Alma Ageyay</button>
        </div>
    </div>
    <hr>

    <p>Lavalle está ubicado a 34 Km, d ela capital provincial, a pocos minutos del aeropuerto internacional. Dispone de atractivos culturales, religiosos, naturales y rurales. Cuenta con servicios y la ventaja de estar cerca de la ciudad de Mendoza.</p>
    <p>Es un nexo hacia otras regiones turísticas importantes como córdoba y el noroeste argentino.</p>
    <p>Existe una gran variedad de atractivos naturales como travesías, médanos, cañadas, bosques autóctonos, lagunas, entre otros. Algunos de ellos han sido protegidos para su preservación, entre ellos encontramos La Reserva Telteca, el complejo Lacunar Huanacache y los bañados del Tulumaya.</p>
    <ul>
        <li>Complejo Lagunar Huanacache. Bañados del Tulumaya</li>
        <li>Sitio Fundacional Algarrobo Histórico</li>
        <li>Museo de Lagunas del Rosario, Museo de Sitio de La Asunción</li>
        <li>Pueblos originarios, capillas históricas y fiestas religiosas</li>
        <li>Lagunas del Rosario, La Asunción, San José, El Cavadito.</li>
        <li>Fiesta Departamental de la Vendimia.</li>
        <li>Festival Provincial del Melón y la Sandía. Festival Provincial del Cosechador</li>
        <li>Feria Apicola.</li>
        <li>Festejos del Patrono Civil del Departamento.</li>
    </ul>

</div>
<!-- Modal -->
<div class="modal fade" id="modal-alma" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Alma Ageyay</h4>
            </div>
            <div class="modal-body">
                <center><img src="<?php echo $this->baseUrl(); ?>/img/turismo/alma1.jpg"></center>
                <ul style="list-style: circle">
                    <li><strong style="line-height:20.8px">Contacto:&nbsp;<a href="mailto:Ageyay23@gmail.com" style="line-height: 20.8px;">Ageyay23@gmail.com</a></strong><strong>&nbsp;261-15-4601391</strong></li>
                    <li>EMPRENDIMIENTO ITINERANTE</li>
                    <li>LEYENDA MÚSICA E INTERPRETACIÓN-&nbsp;OBRAS DE TEATRO, ESPECTÁCULO ARTÍSTICO FOLKLÓRICO, TALLERES DE DANZAS VIVENCIALES</li>
                </ul>

                <p><span style="line-height:1.6em">ALMA AGEYAY ES UNA&nbsp;</span><span style="line-height:1.6em">PROPUESTAS PARA REALIZAR CON LOS TURISTAS Y ASISTENTES A ALGÚN EMPRENDIMIENTO DE LA RED O EN LOS MÉDANOS ALTOS LIMPIOS:</span></p>

                <ul style="list-style-type:circle">
                    <li>Narración de leyendas, con actuación y músicos en vivo.</li>
                    <li>Danza teatro con músicos en vivo, representación de cuentos y poemas de escritores Lavallinos.</li>
                    <li>Obras de Teatro Infantil</li>
                    <li>Danzas Folklóricas</li>
                    <li>Taller de Danzas&nbsp; Vivenciales</li>
                </ul>

                <p>Desde tiempos inmemoriales los hombres danzamos y cantamos para expresar lo que nuestra alma siente. Alma Ageyay expresa la cultura popular de leyendas y poetas lavallinos acompañados de músicos en vivo, quienes con percusión y vientos, traen a tu memoria lo que tu alma recuerda. Si le permites a tu alma poner en movimiento su cuerpo, a danzar estás&nbsp; invitado, si al taller de danzas quieres sumarte.</p>

                <p style="text-align: center;"><em><strong>Danzar y cantar en Lavalle ES una experiencia genuina.&nbsp;</strong></em></p>
                <p></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-cosmos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Cosmos</h4>
            </div>
            <div class="modal-body">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">


                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <center><img src="<?php echo $this->baseUrl(); ?>/img/turismo/Cosmos 1.jpg" alt="" class="imagenes-carousel"></center>
                        </div>
                        <div class="item">
                            <center><img src="<?php echo $this->baseUrl(); ?>/img/turismo/Cosmos 2.jpg" alt="" class="imagenes-carousel"></center>
                        </div>
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    </a>
                </div>
                <br>
                <ul style="list-style: none;">
                    <li><strong>Ubicación</strong>: San Martin y 9 de Julio. Villa Tulumaya</li>
                    <li><strong>Teléfono:</strong> 0261- 153336387</li>
                    <li><strong>Sitio Web</strong>: biofincacosmos@yahoo.com.ar</li>
                </ul>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-abuelo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Finca Abuelo Juan</h4>
            </div>
            <div class="modal-body">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">


                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <center><img src="<?php echo $this->baseUrl(); ?>/img/turismo/Abuelo Juan 1.jpg" alt="" class="imagenes-carousel"></center>
                        </div>
                        <div class="item">
                            <center><img src="<?php echo $this->baseUrl(); ?>/img/turismo/Abuelo Juan 2.jpg" alt="" class="imagenes-carousel"></center>
                        </div>
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    </a>
                </div>
                <br>
                <ul style="list-style: none;">
                    <li><strong>Ubicación</strong>: Ruta 34 s/n a 4km. de Villa Tulumaya</li>
                    <li><strong>Teléfono:</strong> 0261- 155615172</li>
                    <li><strong>Sitio Web:</strong> lanzilottarosa@yahoo.com.ar</li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-tecta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Tecta Ti Cuyum</h4>
            </div>
            <div class="modal-body">
                <center><img src="<?php echo $this->baseUrl(); ?>/img/turismo/FOGON.jpg"></center>
                <br>
                <ul style="list-style: none;">
                    <li><strong>Ubicación:</strong> Pueblo de La Asunción</li>
                    <li><strong>Teléfono:</strong> 0261- 156203235</li>
                </ul>
                <p></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-reserva" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Reserva Telteca y Altos Limpios</h4>
            </div>
            <div class="modal-body">

                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">


                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <center><img src="<?php echo $this->baseUrl(); ?>/img/turismo/Altos Limpios.jpg" alt="" class="imagenes-carousel"></center>
                        </div>
                        <div class="item">
                            <center><img src="<?php echo $this->baseUrl(); ?>/img/turismo/Museo 2.jpg" alt="" class="imagenes-carousel"></center>
                        </div>
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-museo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Museo</h4>
            </div>
            <div class="modal-body">
                <center><img src="<?php echo $this->baseUrl() . '/img/turismo/museo.jpg' ?>"></center>
                <br>
                <ul style="list-style: none;">
                    <li><strong>Ubicación</strong>: Ruta 24 y Roque Montenegro&nbsp;</li>
                    <li><strong>Teléfono</strong>: 494- 1097/ 1147</li>
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<!-- 
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
-->