<div class="contenedor botones-sitios">
    <div class="row">

        <?php
        $sitios = $this->sitios;
        $s = new My\Entity\Sitios();

        foreach ($sitios as $s):
            ?>
            <div class="col-md-1 col-sm-6">
                <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#modal-<?php echo $s->getId(); ?>"><?php echo $s->getTitulo(); ?></button>
            </div>
            <?php
        endforeach;
        ?>
    </div>
    <hr>

    <p>Lavalle está ubicado a 34 Km, d ela capital provincial, a pocos minutos del aeropuerto internacional. Dispone de atractivos culturales, religiosos, naturales y rurales. Cuenta con servicios y la ventaja de estar cerca de la ciudad de Mendoza.</p>
    <p>Es un nexo hacia otras regiones turísticas importantes como córdoba y el noroeste argentino.</p>
    <p>Existe una gran variedad de atractivos naturales como travesías, médanos, cañadas, bosques autóctonos, lagunas, entre otros. Algunos de ellos han sido protegidos para su preservación, entre ellos encontramos La Reserva Telteca, el complejo Lacunar Huanacache y los bañados del Tulumaya.</p>
    <ul>
        <li>Complejo Lagunar Huanacache. Bañados del Tulumaya</li>
        <li>Sitio Fundacional Algarrobo Histórico</li>
        <li>Museo de Lagunas del Rosario, Museo de Sitio de La Asunción</li>
        <li>Pueblos originarios, capillas históricas y fiestas religiosas</li>
        <li>Lagunas del Rosario, La Asunción, San José, El Cavadito.</li>
        <li>Fiesta Departamental de la Vendimia.</li>
        <li>Festival Provincial del Melón y la Sandía. Festival Provincial del Cosechador</li>
        <li>Feria Apicola.</li>
        <li>Festejos del Patrono Civil del Departamento.</li>
    </ul>

</div>
<!-- Modal -->
<div class="modal fade" id="modal-alma" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Alma Ageyay</h4>
            </div>
            <div class="modal-body">
                <center><img src="<?php echo $this->baseUrl(); ?>/img/turismo/alma1.jpg"></center>
                <ul style="list-style: circle">
                    <li><strong style="line-height:20.8px">Contacto:&nbsp;<a href="mailto:Ageyay23@gmail.com" style="line-height: 20.8px;">Ageyay23@gmail.com</a></strong><strong>&nbsp;261-15-4601391</strong></li>
                    <li>EMPRENDIMIENTO ITINERANTE</li>
                    <li>LEYENDA MÚSICA E INTERPRETACIÓN-&nbsp;OBRAS DE TEATRO, ESPECTÁCULO ARTÍSTICO FOLKLÓRICO, TALLERES DE DANZAS VIVENCIALES</li>
                </ul>

                <p><span style="line-height:1.6em">ALMA AGEYAY ES UNA&nbsp;</span><span style="line-height:1.6em">PROPUESTAS PARA REALIZAR CON LOS TURISTAS Y ASISTENTES A ALGÚN EMPRENDIMIENTO DE LA RED O EN LOS MÉDANOS ALTOS LIMPIOS:</span></p>

                <ul style="list-style-type:circle">
                    <li>Narración de leyendas, con actuación y músicos en vivo.</li>
                    <li>Danza teatro con músicos en vivo, representación de cuentos y poemas de escritores Lavallinos.</li>
                    <li>Obras de Teatro Infantil</li>
                    <li>Danzas Folklóricas</li>
                    <li>Taller de Danzas&nbsp; Vivenciales</li>
                </ul>

                <p>Desde tiempos inmemoriales los hombres danzamos y cantamos para expresar lo que nuestra alma siente. Alma Ageyay expresa la cultura popular de leyendas y poetas lavallinos acompañados de músicos en vivo, quienes con percusión y vientos, traen a tu memoria lo que tu alma recuerda. Si le permites a tu alma poner en movimiento su cuerpo, a danzar estás&nbsp; invitado, si al taller de danzas quieres sumarte.</p>

                <p style="text-align: center;"><em><strong>Danzar y cantar en Lavalle ES una experiencia genuina.&nbsp;</strong></em></p>
                <p></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<?php
foreach ($sitios as $s):
    ?>
<div class="modal fade" id="modal-<?php echo $s->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel"><?php echo $s->getTitulo(); ?></h4>
                </div>
                <div class="modal-body">
                    <?php
                    $imagenes = $s->getImagenes();
                    $i = new My\Entity\Imagen();

                    if (sizeof($imagenes) > 1) {
                        ?>
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">


                            <!-- Wrapper for slides -->
                            <div class="carousel-inner" role="listbox">

                                <?php
                                $cont = 0;
                                foreach ($imagenes as $i) {

                                    if ($cont == 0) {
                                        ?>
                                        <div class="item active">
                                            <center><img src="<?php echo $this->baseUrl() . '/img/turismo/sitios/' . $i->getUrl(); ?>" alt="" class="imagenes-carousel"></center>
                                        </div>
                                        <?php
                                        $cont++;
                                    } else {
                                        ?>
                                        <div class="item">
                                            <center><img src="<?php echo $this->baseUrl() . '/img/turismo/sitios/' . $i->getUrl(); ?>" alt="" class="imagenes-carousel"></center>
                                        </div>
                                        <?php
                                    }
                                }
                                ?>

                            </div>

                            <!-- Controls -->
                            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            </a>
                        </div>
                        <?php
                    } else if (sizeof($imagenes) == 1) {
                        //ingresara solo una vez
                        foreach ($imagenes as $i) {
                            ?>
                            <center><img src="<?php echo $this->baseUrl() . '/img/turismo/sitios/' . $i->getUrl(); ?>"></center>
                            <?php
                        }
                    }
                    ?>

                    <br>
                    <div style="margin-left: 20px;"><?php echo $s->getContenido(); ?></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    <?php
endforeach;
?>


<!-- 
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
-->