<div class="row">
    <div class="jumbotron">
        <center><h1>Vendimia Lavalle</h1></center>
    </div>
    <div style="padding: 50px;">
        <a class="btn btn-danger btn-lg" style="float: left;" href="<?php echo $this->url(array('controller'=>'vendimia','action'=>'candidatas')); ?>">Candidatas</a>
        <a class="btn btn-warning btn-lg" style="float: right;">Galieria</a>
    </div>
</div>