<div class="row" style="padding-left: 50px;padding-right: 50px;">
    <div class="jumbotron">
        <center><h1>Nueva Candidata <?php echo date('Y'); ?></h1></center>
    </div>
    <div style="display: flex; justify-content: center; align-items: center;">
    <div class="panel panel-default col-md-6">
      <?php
          echo $this->form;
          ?>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function (){
       $("input").css({"marginBottom":"5px"}); 
       
       $("#edad").keyup(function (){
           this.value = (this.value + '').replace(/[^0-9]/g, '');
       });


       $("#estatura").keyup(function (){
           this.value = (this.value + '').replace( /[^0-9.]/g, '');
       });
    });
</script>