<div class="contenedor">
    <div class="contenedor-tab">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <a href="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos25.pdf'; ?>" target="_blank" onclick="window.open(this.href, this.target"><img src="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos25Chica.jpg' ?>" class="img-thumbnail"></a>
            </div>
            <div class="col-md-3 col-sm-6">
                <a href="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos26.pdf'; ?>" target="_blank" onclick="window.open(this.href, this.target"><img src="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos26Chica.jpg' ?>" class="img-thumbnail"></a>
            </div>
            <div class="col-md-3 col-sm-6">
                <a href="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos27.pdf'; ?>" target="_blank" onclick="window.open(this.href, this.target"><img src="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos27Chica.jpg' ?>" class="img-thumbnail"></a>
            </div>
            <div class="col-md-3 col-sm-6">
                <a href="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos28.pdf'; ?>" target="_blank" onclick="window.open(this.href, this.target"><img src="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos28Chica.jpg' ?>" class="img-thumbnail"></a>
            </div>
            
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <a href="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos29.pdf'; ?>" target="_blank" onclick="window.open(this.href, this.target"><img src="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos29Chica.jpg' ?>" class="img-thumbnail"></a>
            </div>
            <div class="col-md-3 col-sm-6">
                <a href="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos30.pdf'; ?>" target="_blank" onclick="window.open(this.href, this.target"><img src="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos30Chica.jpg' ?>" class="img-thumbnail"></a>
            </div>
            <div class="col-md-3 col-sm-6">
                <a href="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos31.pdf'; ?>" target="_blank" onclick="window.open(this.href, this.target"><img src="<?php echo $this->baseUrl() . '/pdf/revistaCrecemos/crecemos31Chica.jpg' ?>" class="img-thumbnail"></a>
            </div>
        </div>
    </div>
</div>