<div class="contendor-tramite">
    <div class="row">

        <?php
        $noticias = $this->nots;
        $n = new My\Entity\Noticia();
        $cont = 0;
        foreach ($noticias as $n):

            if ($n === end($noticias)) {
                ?>
                <input type="hidden" id="ultimoid" value="<?php echo $n->getId(); ?>"/>
                <?php
            }
            if ($cont == 0 || $cont == 4) {
                ?>
                <div class="row">
                    <div class="col-sm-6 col-md-3">
                        <div class="thumbnail thumbnail-noticia">
                            <a href="<?php echo $this->url(array('controller' => 'noticias', 'action' => 'noticia', 'idnoticia' => $n->getId())); ?>"><img src="<?php echo $this->baseUrl() . '/img/noticias/' . $n->getImagennota(); ?>" style="height: 225px; width: 300px;" class="img_not_sec"></a>
                            <div class="caption">
                                <h3><?php echo $n->getTitulo(); ?></h3>
                                <p style="text-align: right; margin: 2px;"><strong><?php echo 'Fecha: ' . date_format(new DateTime($n->getFecha()), 'd-m-Y'); ?></strong></p>
                                <p>
                                    <?php echo $n->getCopete(); ?>
                                </p>
                            </div>
                        </div>
                    </div>
                    <?php
                } else if ($cont == 3 || $cont == 7) {
                    ?>
                    <div class="col-sm-6 col-md-3">
                        <div class="thumbnail thumbnail-noticia">
                            <a href="<?php echo $this->url(array('controller' => 'noticias', 'action' => 'noticia', 'idnoticia' => $n->getId())); ?>"><img src="<?php echo $this->baseUrl() . '/img/noticias/' . $n->getImagennota(); ?>" style="height: 225px; width: 300px;" class="img_not_sec"></a>
                            <div class="caption">
                                <h3><?php echo $n->getTitulo(); ?></h3>
                                <p style="text-align: right; margin: 2px;"><strong><?php echo 'Fecha: ' . date_format(new DateTime($n->getFecha()), 'd-m-Y'); ?></strong></p>
                                <p>
                                    <?php echo $n->getCopete(); ?>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
            } else {
                ?>
                <div class="col-sm-6 col-md-3">
                    <div class="thumbnail thumbnail-noticia">
                        <a href="<?php echo $this->url(array('controller' => 'noticias', 'action' => 'noticia', 'idnoticia' => $n->getId())); ?>"><img src="<?php echo $this->baseUrl() . '/img/noticias/' . $n->getImagennota(); ?>" style="height: 225px; width: 300px;" class="img_not_sec"></a>
                        <div class="caption">
                            <h3><?php echo $n->getTitulo(); ?></h3>
                            <p style="text-align: right; margin: 2px;"><strong><?php echo 'Fecha: ' . date_format(new DateTime($n->getFecha()), 'd-m-Y'); ?></strong></p>
                            <p>
                                <?php echo $n->getCopete(); ?>
                            </p>
                        </div>
                    </div>
                </div>
                <?php
            }

            $cont++;
        endforeach;
        ?>

    </div>
</div>