<?php
$noticias = $this->nots;
$ultimoele = $this->ultimo;
?>
<div class="contendor-tramite">
    <div class="row" id="noticias">

        <?php
        $n = new My\Entity\Noticia();
        $cont = 0;
        foreach ($noticias as $n):

            if ($n === end($noticias)) {
                ?>
                <input type="hidden" id="ultimoid" value="<?php echo $n->getId(); ?>"/>
                <?php
            }
            if ($cont == 0 || $cont == 4) {
                ?>
                <div class="row">
                    <div class="col-sm-6 col-md-3">
                        <div class="thumbnail thumbnail-noticia">
                            <a href="<?php echo $this->url(array('controller' => 'noticias', 'action' => 'noticia', 'idnoticia' => $n->getId())); ?>"><img src="<?php echo $this->baseUrl() . '/img/noticias/' . $n->getImagennota(); ?>" style="height: 225px; width: 300px;" class="img_not_sec"></a>
                            <div class="caption">
                                <h3><?php echo $n->getTitulo(); ?></h3>
                                <p style="text-align: right; margin: 2px;"><strong><?php echo 'Fecha: ' . date_format(new DateTime($n->getFecha()), 'd-m-Y'); ?></strong></p>
                                <p>
                                    <?php echo $n->getCopete(); ?>
                                </p>
                            </div>
                        </div>
                    </div>
                    <?php
                } else if ($cont == 3 || $cont == 7) {
                    ?>
                    <div class="col-sm-6 col-md-3">
                        <div class="thumbnail thumbnail-noticia">
                            <a href="<?php echo $this->url(array('controller' => 'noticias', 'action' => 'noticia', 'idnoticia' => $n->getId())); ?>"><img src="<?php echo $this->baseUrl() . '/img/noticias/' . $n->getImagennota(); ?>" style="height: 225px; width: 300px;" class="img_not_sec"></a>
                            <div class="caption">
                                <h3><?php echo $n->getTitulo(); ?></h3>
                                <p style="text-align: right; margin: 2px;"><strong><?php echo 'Fecha: ' . date_format(new DateTime($n->getFecha()), 'd-m-Y'); ?></strong></p>
                                <p>
                                    <?php echo $n->getCopete(); ?>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
            } else {
                ?>
                <div class="col-sm-6 col-md-3">
                    <div class="thumbnail thumbnail-noticia">
                        <a href="<?php echo $this->url(array('controller' => 'noticias', 'action' => 'noticia', 'idnoticia' => $n->getId())); ?>"><img src="<?php echo $this->baseUrl() . '/img/noticias/' . $n->getImagennota(); ?>" style="height: 225px; width: 300px;" class="img_not_sec"></a>
                        <div class="caption">
                            <h3><?php echo $n->getTitulo(); ?></h3>
                            <p style="text-align: right; margin: 2px;"><strong><?php echo 'Fecha: ' . date_format(new DateTime($n->getFecha()), 'd-m-Y'); ?></strong></p>
                            <p>
                                <?php echo $n->getCopete(); ?>
                            </p>
                        </div>
                    </div>
                </div>
                <?php
            }

            $cont++;
        endforeach;
        ?>

    </div>

    <div class="row">
        <nav aria-label="...">
            <ul class="pager">
                <li class="previous disabled" id="paginaanterior"><a id="paginaanterior" onclick="traernoticias('anterior')"><span aria-hidden="true">&larr;</span> Anterior</a></li>
                <li class="next"><a  id="paginasiguiente" onclick="traernoticias('siguiente')">Siguiente <span aria-hidden="true">&rarr;</span></a></li>
            </ul>
        </nav>
    </div>

</div>

<script type="text/javascript">
    var maximo = $("#ultimoid").val();


    function traernoticias(accion) {
        var ultimoid = $("#ultimoid").val();

        if (accion == "anterior" && ultimoid < maximo) {
            ejecutar(ultimoid,accion);
        } else if (accion == "anterior" && ultimoid >= maximo) {
            alert("No hay noticias nuevas.");
        } else if (accion = "siguiente") {
            ejecutar(ultimoid,accion);
        }


    }


    function ejecutar(ultimoid,accion) {
        var request = $.ajax({
            url: "/paginamuni/public/noticias/mas-noticias/ultimoid/" + ultimoid + "/accion/" + accion,
            method: "GET",
            dataType: "html"
        });

        request.done(function (msg) {
            $("#noticias").html(msg);
            var ultimoid = $("#ultimoid").val();
            if (ultimoid >= maximo) {
                $("#paginaanterior").addClass("disabled");
            } else {
                $("#paginaanterior").removeClass("disabled");
            }
        });

        request.fail(function (jqXHR, textStatus) {
            alert("Request failed: " + textStatus);
        });
    }
</script>